import {syncMemory,agentTrace,performanceReport,readinessReport} from './insights.mjs';
import {learningScorecard} from './knowledge.mjs';
import {evaluationReport} from './evaluation.mjs';
import {saveResearchConnection} from './connections.mjs';
import {monitoringSummary,recordMonitoringAttempt,recordMonitoringSuccess,recordMonitoringFailure,updateMonitoringHealth} from './monitoring.mjs';
import {testingReadiness} from './testing-readiness.mjs';
import {agentSkillSummary,updateAgentSkills} from './agent-skill.mjs';
import {researchTrialsControl,researchTrialsSummary,updateResearchTrials} from './research-trials.mjs';
import {gmgnSummary,getWalletResearch,gmgnConnection,gmgnDiscover,gmgnAnalyze,gmgnActivity,gmgnWatch} from './gmgn.mjs';
import {runResearch,researchControl,researchSummary,evaluateResearch} from "./research.mjs";
import {updateSimulation,simulationSummary,simulationControl,simulationDiagnostic} from "./simulation.mjs";
import {updateLearning,learningSummary} from "./learning.mjs";
import {readState,mutate,accountSummary,controls,order,tickStateV2 as tickState,replayV2 as replay,fillDiagnostic,marketKey,fresh,signalFor} from "./paper.mjs";
const STOCKS=['NVDA','TSLA','AAPL','SPY'];
const CRYPTO=['BTC/USD'];
const ALPACA_PAPER_ORIGIN='https://paper-api.alpaca.markets/v2';
export const PUBLIC_SOURCES={solana:'https://api.dexscreener.com/latest/dex/search?q=SOL',prediction:'https://gamma-api.polymarket.com/markets?closed=false&active=true&limit=12&order=volume24hr&ascending=false',kalshi:'https://api.elections.kalshi.com/trade-api/v2/markets?limit=12&status=open'};
const number=v=>v!==null&&v!==undefined&&v!==''&&Number.isFinite(Number(v))?Number(v):null;
async function fetchJson(url,headers={}){const r=await fetch(url,{headers:{accept:'application/json',...headers},signal:AbortSignal.timeout(10000)});if(!r.ok){const error=new Error('Source returned HTTP '+r.status);error.http_status=r.status;const retry=r.headers.get('Retry-After');if(retry){const seconds=Number(retry);error.retry_after=Number.isFinite(seconds)?Date.now()+Math.max(0,seconds)*1000:Date.parse(retry)}throw error;}return r.json()}
function alpacaReady(env){return env.ALPACA_API_KEY&&env.ALPACA_API_SECRET&&env.ALPACA_PAPER_BASE_URL===ALPACA_PAPER_ORIGIN}
function alpacaHeaders(env){return{'APCA-API-KEY-ID':env.ALPACA_API_KEY,'APCA-API-SECRET-KEY':env.ALPACA_API_SECRET,'Content-Type':'application/json','Accept':'application/json'}}
async function alpacaJson(env,path,options={}){if(!alpacaReady(env))throw Error('Alpaca Paper is not configured with the locked paper endpoint');const r=await fetch(ALPACA_PAPER_ORIGIN+path,{...options,headers:{...alpacaHeaders(env),...(options.headers||{})},signal:AbortSignal.timeout(12000)});const text=await r.text();let value={};try{value=text?JSON.parse(text):{}}catch{value={message:text||'Invalid Alpaca response'}}if(!r.ok){const error=new Error('Alpaca Paper: '+(value.message||('HTTP '+r.status)));error.http_status=r.status;throw error}return value}
async function alpacaSnapshot(env){if(!alpacaReady(env))return{status:'not_configured',paper_endpoint_locked:true,orders:[],positions:[]};const [account,positions,orders]=await Promise.all([alpacaJson(env,'/account'),alpacaJson(env,'/positions'),alpacaJson(env,'/orders?status=all&limit=100&direction=desc')]);return{status:'connected',paper_endpoint_locked:true,synced_at:new Date().toISOString(),account:{id:account.id,status:account.status,currency:account.currency,cash:number(account.cash),equity:number(account.equity),buying_power:number(account.buying_power),portfolio_value:number(account.portfolio_value),pattern_day_trader:Boolean(account.pattern_day_trader),trading_blocked:Boolean(account.trading_blocked)},positions:(positions||[]).map(p=>({symbol:p.symbol,qty:number(p.qty),side:p.side,avg_entry_price:number(p.avg_entry_price),market_value:number(p.market_value),current_price:number(p.current_price),unrealized_pl:number(p.unrealized_pl),unrealized_plpc:number(p.unrealized_plpc)})),orders:(orders||[]).map(o=>({id:o.id,client_order_id:o.client_order_id,symbol:o.symbol,side:o.side,type:o.type,time_in_force:o.time_in_force,qty:number(o.qty),filled_qty:number(o.filled_qty),filled_avg_price:number(o.filled_avg_price),status:o.status,submitted_at:o.submitted_at,filled_at:o.filled_at,canceled_at:o.canceled_at,rejected_at:o.rejected_at}))}}
async function clientOrderId(intent){const bytes=new TextEncoder().encode(intent);const digest=await crypto.subtle.digest('SHA-256',bytes);return'dots-'+[...new Uint8Array(digest)].slice(0,16).map(x=>x.toString(16).padStart(2,'0')).join('')}
export function reconcileBrokerState(state,broker,at=Date.now()){const changes=[];if(!Array.isArray(broker?.orders))return changes;state.broker_requests=state.broker_requests||{};state.alerts=state.alerts||[];const terminal=new Set(['filled','canceled','expired','rejected','replaced','done_for_day']);for(const request of Object.values(state.broker_requests)){const result=request?.result;if(!result?.broker_order_id)continue;const order=broker.orders.find(o=>o.id===result.broker_order_id||o.client_order_id===result.client_order_id);if(!order||order.status===result.broker_status)continue;const previous=result.broker_status;Object.assign(result,{broker_status:order.status,filled_quantity:number(order.filled_qty)||0,filled_avg_price:number(order.filled_avg_price),filled_at:order.filled_at||null,canceled_at:order.canceled_at||null,rejected_at:order.rejected_at||null});request.status=terminal.has(order.status)?order.status:'submitted';request.updated_at=at;const message='Alpaca Paper '+result.side+' '+result.symbol+' · '+order.status;const alert=state.alerts.find(a=>a.type==='broker_order'&&!a.resolved_at&&a.message.includes(result.symbol));if(alert){alert.message=message;alert.updated_at=at}else state.alerts.unshift({id:crypto.randomUUID(),type:'broker_order',message,at,ref:'VEGA',read:false});changes.push({symbol:result.symbol,previous,status:order.status})}state.alerts=state.alerts.slice(0,500);return changes}
const smartDefaults={risk_per_trade_pct:.5,stop_loss_pct:2,take_profit_pct:4,trailing_stop_pct:1.5,trailing_activation_pct:2,max_crypto_hold_hours:72,max_stock_hold_hours:48,min_consensus_score:100};
export function smartPolicy(state){return{...smartDefaults,...(state.smart_policy||{})}}
const compactSymbol=s=>String(s||'').replaceAll('/','');
export function brokerTradeReport(broker){
 const lots=new Map(),trades=[];let complete=true;
 const fills=(broker?.orders||[]).filter(o=>(number(o.filled_qty)||0)>0&&number(o.filled_avg_price)>0).sort((a,b)=>Date.parse(a.filled_at||a.submitted_at)-Date.parse(b.filled_at||b.submitted_at));
 for(const o of fills){const key=compactSymbol(o.symbol),queue=lots.get(key)||[];lots.set(key,queue);let remaining=Number(o.filled_qty);
  if(o.side==='buy'){queue.push({qty:remaining,price:Number(o.filled_avg_price)});continue}
  if(o.side!=='sell')continue;let basis=0,matched=0;
  while(remaining>1e-12&&queue.length){const lot=queue[0],qty=Math.min(remaining,lot.qty);basis+=qty*lot.price;matched+=qty;remaining-=qty;lot.qty-=qty;if(lot.qty<1e-12)queue.shift()}
  const reconciled=remaining<1e-12;if(!reconciled)complete=false;
  trades.push({order_id:o.id,symbol:o.symbol,at:o.filled_at||o.submitted_at,quantity:Number(o.filled_qty),matched_quantity:matched,cost_basis:reconciled?basis:null,proceeds:Number(o.filled_qty)*Number(o.filled_avg_price),gross_pnl:reconciled?Number(o.filled_qty)*Number(o.filled_avg_price)-basis:null,fees:null,net_pnl:null,status:reconciled?'gross_reconciled':'missing_entry_history'});
 }
 return{trades,gross_realized_pnl:complete?trades.reduce((s,t)=>s+t.gross_pnl,0):null,net_realized_pnl:null,fees:null,history_complete:complete&&(broker?.orders||[]).length<100,note:'FIFO matched broker fill quantities. Gross P&L excludes fees and crypto quantity deductions; net P&L remains unknown until broker costs are supplied.'};
}
export function deskAgentCards({sources=[],markets=[],broker={},autonomy={},risk={}},now=Date.now()){
 const freshMarkets=markets.filter(m=>m.tradable_fresh!==false&&now-Date.parse(m.quote_at||m.fetched_at||0)<=90000),healthySources=sources.filter(s=>s.status==='connected').length;
 const sourceIssues=sources.filter(s=>!['connected','empty'].includes(s.status)),openOrders=(broker.orders||[]).filter(o=>['new','accepted','pending_new','partially_filled','held','pending_replace','calculated'].includes(o.status)),positions=broker.positions||[];
 const regimes=Object.entries(autonomy.regimes||{}),topRegime=regimes.sort((a,b)=>(b[1]?.confidence||0)-(a[1]?.confidence||0))[0],consensus=Number(autonomy.consensus_score)||0;
 const riskBlocked=risk.health==='blocked'||risk.health==='halted'||risk.uncertain_pending||risk.stale_positions>0;
 return[
  {name:'ATLAS',role:'SCAN',status:freshMarkets.length?'working':'waiting',reason:freshMarkets.length?`Scanning ${freshMarkets.length} fresh quotes across ${healthySources}/${sources.length} sources`:'Waiting for fresh market quotes'},
  {name:'NOVA',role:'VET',status:autonomy.status==='shadow'?'working':'waiting',reason:autonomy.status==='shadow'?`Reviewing ${autonomy.symbol||'candidate'} signal · ${consensus}% gates`:`Checking signals · ${consensus}% current gate consensus`},
  {name:'ORION',role:'RESEARCH',status:sourceIssues.length?'warning':'working',reason:sourceIssues.length?`Source watch · ${sourceIssues.map(s=>`${s.key} ${String(s.status).replaceAll('_',' ')}`).join(', ')}`:`Research feeds healthy · ${healthySources}/${sources.length} connected`},
  {name:'TITAN',role:'REGIME',status:regimes.length?'working':'waiting',reason:topRegime?`Modeling ${regimes.length} regimes · ${topRegime[0]} ${String(topRegime[1].kind).replaceAll('_',' ')} ${topRegime[1].confidence}%`:'Waiting for enough price history'},
  {name:'VEGA',role:'SIZE',status:riskBlocked?'warning':'working',reason:riskBlocked?'Sizing blocked until exposure is verified':`Sizing ready · $${Number(risk.ticket_limit||0).toFixed(0)} ticket · $${Number(risk.exposure_remaining||0).toFixed(0)} headroom`},
  {name:'LUNA',role:'RISK',status:riskBlocked?'warning':'working',reason:riskBlocked?`Risk ${risk.health||'blocked'} · review desk state`:`Risk clear · ${positions.length} positions · ${openOrders.length} pending orders`}
 ];
}
export function monitoringAnalysis(state,now=Date.now()){
 const risk=sharedRisk(state,state.broker,now),policy=smartPolicy(state),base={at:now,enabled:true,mode:'shadow_only',strategy:'Recorded quote signals; no execution',orders_submitted:0};
 if(state.broker?.status==='unavailable')return{...base,status:'blocked',reason:'Broker reconciliation unavailable'};
 const exits=(state.broker?.positions||[]).map(p=>({symbol:p.symbol,...positionExitPlan(p,policy,state.position_meta?.[compactSymbol(p.symbol)],now)})).filter(p=>p.action==='sell');
 if(exits.length)return{...base,status:'exit_review',reason:'Protective exit needs a signed-in manual paper order',exit_reviews:exits};
 if(!state.running||state.halted||risk.stale_positions||risk.uncertain_pending)return{...base,status:'paused',reason:'Entry analysis blocked by desk or data state'};
 const candidates=[];for(const q of state.markets.filter(q=>q.venue==='Alpaca'&&['crypto','stocks'].includes(q.asset_class))){const samples=state.observations.filter(o=>o.market_id===marketKey(q)&&now-o.at<(q.asset_class==='crypto'?86400000:14400000)),regime=marketRegime(samples),signal=q.asset_class==='crypto'?(samples.length>=20&&regime.kind==='uptrend'?'buy':'hold'):signalFor(samples),spread=(q.ask-q.bid)/q.ask;
  const gates={ATLAS:fresh(q,now)&&(q.source_health||0)>=80,ORION:signal==='buy',TITAN:Number.isFinite(spread)&&spread>=0&&spread<=(q.asset_class==='crypto'?.003:.005)&&regime.kind!=='high_volatility',NOVA:!(state.broker?.orders||[]).some(o=>workingOrder(o)&&compactSymbol(o.symbol)===compactSymbol(q.symbol)),VEGA:risk.position_slots_remaining>0&&!(state.broker?.positions||[]).some(p=>compactSymbol(p.symbol)===compactSymbol(q.symbol)),LUNA:risk.exposure_remaining>0};
  if(Object.values(gates).every(Boolean)){const dollars=riskSizedTicket({equity:risk.risk_base,cash:state.cash_cents/100,stop_pct:policy.stop_loss_pct,confidence:regime.confidence,ticket_cap:risk.ticket_limit,exposure_remaining:risk.exposure_remaining});if(dollars>=(q.asset_class==='crypto'?10:1))candidates.push({q,regime,gates,dollars})}
 }
 if(!candidates.length)return{...base,status:'scanning',reason:'No unanimous shadow signal; no orders sent'};const c=candidates[0];return{...base,status:'shadow',reason:'Hypothetical entry recorded; no order sent',symbol:c.q.symbol,gates:c.gates,regime:c.regime,risk_sized_ticket:c.dollars,reference_price:c.q.ask,quote_at:c.q.quote_at||c.q.fetched_at};
}
export async function refreshMonitoring(env,options={}){
 const actor=options.actor==='scheduler'?'scheduler':'browser';
 const token=crypto.randomUUID(),reserved=await mutate(env.DB,s=>{const now=Date.now();if(now-s.last_tick<55000||s.tick_lease?.until>now)return{ok:true,skipped:true,last_tick:s.last_tick,orders_submitted:0};s.tick_lease={token,until:now+120000};recordMonitoringAttempt(s,{actor},now);return{claimed:true}});
 if(!reserved.result.claimed)return reserved.result;
 try{const desk=await collectMarketDesk(env,reserved.state.positions,reserved.state.sources);let broker=null;if(alpacaReady(env)){try{broker=await alpacaSnapshot(env)}catch(e){broker={...reserved.state.broker,status:'unavailable',paper_endpoint_locked:true,error:e.message}}}
  const updated=await mutate(env.DB,s=>{if(s.tick_lease?.token!==token)return{ok:true,skipped:true,orders_submitted:0};const now=Date.now();if(broker){reconcileBrokerState(s,broker,now);updatePositionMeta(s,broker,now);s.broker=broker;
   const report=brokerTradeReport(broker);for(const trade of report.trades){if(!s.alerts.some(a=>a.order_id===trade.order_id&&a.type==='broker_fill'))s.alerts.unshift({id:crypto.randomUUID(),order_id:trade.order_id,type:'broker_fill',at:now,read:false,message:trade.symbol+' sell filled · '+(trade.gross_pnl===null?'cost basis incomplete':'gross P&L $'+trade.gross_pnl.toFixed(2))+' · fees not reconciled'})}s.alerts=s.alerts.slice(0,500)}
   const result=observeMonitoring(s,desk,now);updateLearning(s,now);updateSimulation(s,now);evaluateResearch(s,now);updateAgentSkills(s,now);updateResearchTrials(s,now);
   const analysis=monitoringAnalysis(s,now);recordShadowReview(s,analysis,now);s.autonomy=analysis;s.autonomy_history=[analysis,...(s.autonomy_history||[])].slice(0,200);
   for(const exit of analysis.exit_reviews||[])if(!s.alerts.some(a=>a.type==='exit_review'&&a.symbol===exit.symbol&&!a.resolved_at))s.alerts.unshift({id:crypto.randomUUID(),type:'exit_review',symbol:exit.symbol,at:now,read:false,message:exit.symbol+': '+exit.reason+'; manual paper exit required'});
   recordMonitoringSuccess(s,{actor,quotes:s.markets.filter(q=>fresh(q,now)).length},now);updateMonitoringHealth(s,env,now);s.tick_lease=null;return{...result,monitoring_only:true,broker_status:broker?.status||'not_configured',autonomy_status:analysis.status,autonomous_orders:0,orders_submitted:0}});
  if(updated.result.skipped)return updated.result;
  let research;try{research=await runResearch(env,{},true);}catch{research={status:'research_failed'};}
  const {state:memoryState}=await readState(env.DB);await syncMemory(env,memoryState);return{...updated.result,research_status:research.status||'idle'};
 }catch(error){await mutate(env.DB,s=>{if(s.tick_lease?.token===token){s.tick_lease=null;recordMonitoringFailure(s,{actor},Date.now());updateMonitoringHealth(s,env);}});throw error}
}
export function observeMonitoring(s,desk,now=Date.now()){
 s.markets=desk.markets.map(q=>({...q,collected_at:q.cached?(s.markets.find(p=>marketKey(p)===marketKey(q)&&p.quote_at===q.quote_at)?.collected_at||null):new Date(now).toISOString()}));s.sources=desk.sources;s.last_tick=now;
 for(const source of desk.sources){const incidents=s.alerts.filter(a=>a.type==='connection'&&a.source_key===source.key&&!a.resolved_at);
  if(['connected','empty'].includes(source.status)){for(const a of incidents){a.resolved_at=now;a.read=true}if(incidents.length)s.alerts.unshift({id:crypto.randomUUID(),type:'connection_recovered',source_key:source.key,message:source.key+': Connection recovered',at:now,read:false})}
  else if(['rate_limited','unavailable'].includes(source.status)){const a=incidents[0];if(a)Object.assign(a,{message:source.key+': '+source.error,updated_at:now,retry_at:source.retry_at});else s.alerts.unshift({id:crypto.randomUUID(),type:'connection',source_key:source.key,message:source.key+': '+source.error,at:now,read:false,retry_at:source.retry_at})}
 }
 for(const q of desk.markets)if(fresh(q,now))s.observations.push({market_id:marketKey(q),symbol:q.symbol,asset_class:q.asset_class,at:now,quote_at:['stocks','crypto'].includes(q.asset_class)?q.quote_at||null:q.quote_at||q.fetched_at,price:q.price,bid:q.bid??q.yes_bid,ask:q.ask??q.yes_ask});s.observations=s.observations.slice(-12000);
 const summary=accountSummary(s,now);s.history.push({at:now,equity:summary.equity,cash:summary.cash});s.history=s.history.slice(-3000);s.alerts=s.alerts.slice(0,500);
 return{ok:true,quotes:desk.markets.length,last_tick:now};
}
const workingOrder=o=>!['filled','canceled','expired','rejected','replaced','done_for_day'].includes(o.status);
export function recordShadowReview(state,cycle,now=Date.now()){
 state.shadow_reviews=state.shadow_reviews||[];
 for(const review of state.shadow_reviews){
  if(review.outcome||now-review.at<3600000)continue;
  const q=state.markets.find(q=>q.symbol===review.symbol);
  if(!fresh(q,now)||!(q.bid>0))continue;
  if(now-review.at>7200000){review.outcome={status:'missed_window',at:now};continue}
  review.outcome={status:'evaluated',at:now,horizon_minutes:(now-review.at)/60000,exit_bid:q.bid,modeled_return_pct:(q.bid*.999/(review.entry_ask*1.001)-1)*100,assumption:'Observed bid/ask plus 0.1% modeled fee per side; not an actual fill'};
 }
 if(cycle.status!=='shadow'||!cycle.symbol||!(cycle.reference_price>0))return;
 const key=cycle.symbol+':'+cycle.quote_at;
 if(state.shadow_reviews.some(r=>r.key===key||r.symbol===cycle.symbol&&now-r.at<3600000))return;
 state.shadow_reviews.unshift({key,at:now,symbol:cycle.symbol,entry_ask:cycle.reference_price,quote_at:cycle.quote_at,dollars:cycle.risk_sized_ticket,gates:cycle.gates,regime:cycle.regime,origin:'deterministic_rules',executed:false,challenge:['No independent language-model review connected','Quote-sample trend is not a validated trading edge','Spread, fees and changing volatility can erase apparent gains']});
 state.shadow_reviews=state.shadow_reviews.slice(0,200);
}
export function shadowSummary(state,now=Date.now()){
 const reviews=state.shadow_reviews||[],scored=reviews.filter(r=>r.outcome?.status==='evaluated');
 return{mode:'shadow_only',chatgpt_connected:false,api_billing_enabled:false,analysis_type:'Programmed checks, not ChatGPT models',entry_execution_enabled:false,generated_at:new Date(now).toISOString(),reviews:reviews.slice(0,50),evaluated:scored.length,mean_modeled_return_pct:scored.length?scored.reduce((s,r)=>s+r.outcome.modeled_return_pct,0)/scored.length:null,validation:'No strategy promotion based on these observations alone',limitations:['No news feed or external research model connected','Net broker P&L requires verified fees and complete fill history','Exit conditions generate alerts; refresh never executes orders']};
}
export function sharedRisk(state,broker=state.broker,now=Date.now()){
 const summary=accountSummary(state,now),base=Number.isFinite(summary.equity)?summary.equity:0;
 const positions=broker?.positions||[],pending=(broker?.orders||[]).filter(o=>o.side==='buy'&&workingOrder(o));
 const internal=(summary.positions||[]).reduce((n,p)=>n+(p.mark??p.cost_cents/100),0);
 const external=positions.reduce((n,p)=>n+Math.abs(number(p.market_value)||0),0);
 let uncertain=false;
 const reserved=pending.reduce((n,o)=>{const q=state.markets.find(q=>compactSymbol(q.symbol)===compactSymbol(o.symbol));const qty=Math.max(0,(number(o.qty)||0)-(number(o.filled_qty)||0));if(!qty||!(q?.ask>0)){uncertain=true;return n}return n+qty*q.ask*1.01},0);
 const staleInternal=(summary.positions||[]).filter(p=>p.mark===null).length;
 const synced=Date.parse(broker?.synced_at),staleBroker=positions.filter(p=>broker?.status!=='connected'||!Number.isFinite(synced)||now-synced>90000||synced>now||!Number.isFinite(number(p.current_price))||!Number.isFinite(number(p.market_value))).length;
 const limit=base*state.config.exposure_pct/100,available=Math.max(0,limit-internal-external-reserved);
 const slots=new Set([...positions,...pending].map(p=>compactSymbol(p.symbol))).size+state.positions.length;
 const cash=Math.max(0,Math.min(summary.cash,number(broker?.account?.cash)??summary.cash));
 return{scope:'combined_paper',risk_base:base,exposure:internal+external,internal_exposure:internal,broker_exposure:external,reserved_exposure:reserved,exposure_pct:base?(internal+external)/base*100:0,exposure_limit:limit,exposure_remaining:uncertain?0:available,ticket_limit:Math.max(0,cash*state.config.ticket_pct/100),position_slots_remaining:Math.max(0,state.config.max_positions-slots),fresh_positions:state.positions.length+positions.length-staleInternal-staleBroker,stale_positions:staleInternal+staleBroker,uncertain_pending:uncertain};
}
export function marketRegime(samples=[]){const clean=samples.filter(x=>Number.isFinite(number(x.price))).slice(-30),prices=clean.map(x=>number(x.price));if(prices.length<6)return{kind:'insufficient_data',confidence:0,volatility_pct:null,momentum_pct:null};const returns=prices.slice(1).map((p,i)=>(p-prices[i])/prices[i]),mean=returns.reduce((a,b)=>a+b,0)/returns.length,variance=returns.reduce((a,b)=>a+(b-mean)**2,0)/returns.length,volatility=Math.sqrt(variance)*100,momentum=(prices.at(-1)-prices[0])/prices[0]*100;let kind='range';if(volatility>3)kind='high_volatility';else if(Math.abs(momentum)>1)kind=momentum>0?'uptrend':'downtrend';return{kind,confidence:Math.min(100,Math.round(prices.length/30*60+Math.min(40,Math.abs(momentum)*12))),volatility_pct:volatility,momentum_pct:momentum,samples:prices.length}}
export function riskSizedTicket({equity,cash,stop_pct,confidence=100,ticket_cap,exposure_remaining}){const values=[equity,cash,stop_pct,confidence,ticket_cap,exposure_remaining];if(values.some(v=>!Number.isFinite(v))||stop_pct<=0)return 0;return Math.max(0,Math.min(equity*.005/(stop_pct/100)*Math.max(0,Math.min(1,confidence/100)),cash,ticket_cap,exposure_remaining))}
export function positionExitPlan(position,policy=smartDefaults,meta={},at=Date.now()){const entry=number(position.avg_entry_price),current=number(position.current_price);if(!entry||!current)return{action:'hold',reason:'Waiting for a valid broker mark',pnl_pct:null};const pnlPct=(current-entry)/entry*100,peak=Math.max(current,number(meta.high_water)||current),ageHours=meta.opened_at?Math.max(0,(at-meta.opened_at)/3600000):0,isCrypto=compactSymbol(position.symbol).includes('BTC')||compactSymbol(position.symbol).includes('ETH'),maxHours=isCrypto?policy.max_crypto_hold_hours:policy.max_stock_hold_hours,stop=entry*(1-policy.stop_loss_pct/100),target=entry*(1+policy.take_profit_pct/100),trailing=peak*(1-policy.trailing_stop_pct/100),trailActive=peak>=entry*(1+policy.trailing_activation_pct/100);if(current<=stop)return{action:'sell',reason:'Hard stop reached',pnl_pct:pnlPct,trigger_price:stop,high_water:peak,age_hours:ageHours};if(current>=target)return{action:'sell',reason:'Profit target reached',pnl_pct:pnlPct,trigger_price:target,high_water:peak,age_hours:ageHours};if(trailActive&&current<=trailing)return{action:'sell',reason:'Trailing stop reached',pnl_pct:pnlPct,trigger_price:trailing,high_water:peak,age_hours:ageHours};if(ageHours>=maxHours)return{action:'sell',reason:'Maximum holding time reached',pnl_pct:pnlPct,trigger_price:current,high_water:peak,age_hours:ageHours};return{action:'hold',reason:trailActive?'Trailing stop armed':'Inside stop and target',pnl_pct:pnlPct,stop_price:stop,target_price:target,trailing_price:trailActive?trailing:null,high_water:peak,age_hours:ageHours}}
export function consecutiveLosses(orders=[]){let count=0;for(const order of orders.filter(x=>x.side==='sell'&&x.status==='filled').sort((a,b)=>Date.parse(b.filled_at||b.submitted_at)-Date.parse(a.filled_at||a.submitted_at))){const pnl=number(order.realized_pl);if(pnl===null)break;if(pnl<0)count++;else break}return count}
export function updatePositionMeta(state,broker,at=Date.now()){state.position_meta=state.position_meta||{};const active=new Set;for(const position of broker?.positions||[]){const key=compactSymbol(position.symbol);active.add(key);const prior=state.position_meta[key]||{};state.position_meta[key]={opened_at:prior.opened_at||Date.parse((broker.orders||[]).filter(o=>compactSymbol(o.symbol)===key&&o.side==='buy'&&o.status==='filled').sort((a,b)=>Date.parse(b.filled_at)-Date.parse(a.filled_at))[0]?.filled_at)||at,high_water:Math.max(number(prior.high_water)||0,number(position.current_price)||0),updated_at:at}}for(const key of Object.keys(state.position_meta))if(!active.has(key))delete state.position_meta[key];return state.position_meta}
async function submitAlpacaPaperOrder(env,state,input){if(typeof input.intent_id!=='string'||!input.intent_id||input.intent_id.length>128)throw Error('A unique intent_id is required');if(!['buy','sell'].includes(input.side))throw Error('Choose buy or sell');if(input.side==='buy'&&(!state.running||state.halted))throw Error(state.halted?'Desk is halted':'Start the paper desk before submitting an order');const quote=state.markets.find(q=>marketKey(q)===input.market_id);if(!quote||!['stocks','crypto'].includes(quote.asset_class)||quote.venue!=='Alpaca')throw Error('Only Alpaca stock or crypto quotes can route to Alpaca Paper');
 if(!fresh(quote,Date.now()))throw Error('No fresh server quote is available');const spread=(quote.ask-quote.bid)/quote.ask,maxSpread=quote.asset_class==='crypto'?.01:.03;if(!Number.isFinite(quote.bid)||!Number.isFinite(quote.ask)||quote.bid<=0||quote.ask<quote.bid||spread>maxSpread)throw Error('Bid/ask book is missing, crossed, or wider than '+(maxSpread*100)+'%');if(quote.asset_class==='crypto'&&(quote.source_health||0)<80)throw Error('Crypto source health must be at least 80 before entry');
 if(Object.values(state.broker_requests||{}).some(r=>r.status==='uncertain'))throw Error('Uncertain broker submission requires reconciliation before further orders');const snapshot=await alpacaSnapshot(env);if(snapshot.account.trading_blocked)throw Error('Alpaca Paper reports trading is blocked');const equity=snapshot.account.equity||0,cash=snapshot.account.cash||0,exposure=snapshot.positions.reduce((sum,p)=>sum+Math.abs(p.market_value||0),0);
 let qty;
 if(input.side==='buy'){const dailyStart=state.broker_daily?.[new Date().toISOString().slice(0,10)]?.start_equity;if(Number.isFinite(dailyStart)&&snapshot.account.equity<=dailyStart-state.initial_cents/100*state.config.daily_loss_pct/100)throw Error('Desk-base daily loss limit reached');const requested=number(input.dollars);if(!requested||requested<=0)throw Error('Enter a positive dollar amount');if(quote.asset_class==='crypto'&&requested<10)throw Error('Crypto paper entries must be at least $10');
  const risk=sharedRisk(state,snapshot);if(risk.stale_positions||risk.uncertain_pending)throw Error('Fresh reconciled exposure is required');if(!risk.position_slots_remaining)throw Error('Position slots exhausted');if(snapshot.positions.some(p=>compactSymbol(p.symbol)===compactSymbol(quote.symbol))||snapshot.orders.some(o=>workingOrder(o)&&compactSymbol(o.symbol)===compactSymbol(quote.symbol)))throw Error('Existing position or working order blocks entry');const budget=Math.min(requested,risk.ticket_limit,risk.exposure_remaining,cash);qty=Math.floor(budget/quote.ask*1e6)/1e6;if(qty<=0||qty*quote.ask<(quote.asset_class==='crypto'?10:1))throw Error('No viable ticket fits the paper cash and risk limits')}else{const compact=s=>String(s||'').replaceAll('/','');const position=snapshot.positions.find(p=>compact(p.symbol)===compact(quote.symbol));if(position?.side!=='long')throw Error('Only a long position can be reduced by selling');if(snapshot.orders.some(o=>workingOrder(o)&&compact(o.symbol)===compact(quote.symbol)))throw Error('Working order blocks duplicate exit');qty=position?Math.abs(position.qty):0;if(qty<=0)throw Error('No Alpaca Paper position is available to close')}const id=await clientOrderId(input.intent_id);let broker;try{broker=await alpacaJson(env,'/orders',{method:'POST',body:JSON.stringify({symbol:quote.symbol,qty:String(qty),side:input.side,type:'market',time_in_force:quote.asset_class==='crypto'?'gtc':'day',client_order_id:id})})}catch(error){error.submission_unknown=!error.http_status||error.http_status>=500;throw error}return{status:'submitted',mode:'alpaca_paper',broker_order_id:broker.id,client_order_id:id,symbol:broker.symbol,side:broker.side,quantity:number(broker.qty),filled_quantity:number(broker.filled_qty)||0,filled_avg_price:number(broker.filled_avg_price),broker_status:broker.status,submitted_at:broker.submitted_at,paper_endpoint_locked:true}}
async function autonomousPaperCycle(env,state){
 const at=Date.now(),policy=smartPolicy(state),base={at,enabled:env.AUTONOMOUS_PAPER_ENABLED==='true',mode:'alpaca_paper',strategy:'regime-aware stock and crypto consensus',orders_submitted:0,policy};
 if(!base.enabled)return{...base,status:'disabled',reason:'Autonomous paper mode is disabled'};
 // Stopping entries must not disable risk-reducing exits.
 if(Object.values(state.broker_requests||{}).some(r=>r.status==='uncertain'))return{...base,status:'blocked',reason:'Uncertain broker submission requires reconciliation'};const snapshot=await alpacaSnapshot(env);if(snapshot.account.trading_blocked)return{...base,status:'blocked',reason:'Alpaca Paper reports trading is blocked'};
 const day=new Date(at).toISOString().slice(0,10),start=state.broker_daily?.[day]?.start_equity||snapshot.account.equity;
 const riskBudget=(state.initial_cents/100)*state.config.daily_loss_pct/100,dailyBreached=snapshot.account.equity<=start-riskBudget;
 const openStatuses=new Set(['new','accepted','pending_new','partially_filled','held','pending_replace','accepted_for_bidding','calculated']),openSymbols=new Set(snapshot.orders.filter(o=>openStatuses.has(o.status)).map(o=>compactSymbol(o.symbol)));
 for(const position of snapshot.positions){
  const quote=state.markets.find(q=>q.venue==='Alpaca'&&compactSymbol(q.symbol)===compactSymbol(position.symbol)),plan=positionExitPlan(position,policy,state.position_meta?.[compactSymbol(position.symbol)],at);
  if(plan.action==='sell'&&quote&&!openSymbols.has(compactSymbol(position.symbol))){const result=await submitAlpacaPaperOrder(env,state,{intent_id:'managed-exit:'+compactSymbol(position.symbol)+':'+plan.reason+':'+(state.position_meta?.[compactSymbol(position.symbol)]?.opened_at||position.avg_entry_price),market_id:marketKey(quote),side:'sell'});return{...base,status:'submitted',reason:plan.reason,orders_submitted:1,signal:'sell',symbol:quote.symbol,managed_exit:plan,result,start_equity:start,equity:snapshot.account.equity}}
 }
 if(dailyBreached)return{...base,status:'halted',reason:'Broker daily loss exceeds the desk-base loss budget',start_equity:start,equity:snapshot.account.equity};
 if(!state.running||state.halted)return{...base,status:'paused',reason:state.halted?(state.halt_reason||'Desk halted'):'Entries stopped; protective exits still checked'};
 const clock=await alpacaJson(env,'/clock'),candidates=[];
 for(const q of state.markets.filter(q=>['stocks','crypto'].includes(q.asset_class)&&q.venue==='Alpaca')){
  const samples=state.observations.filter(o=>o.market_id===marketKey(q)&&at-o.at<(q.asset_class==='crypto'?86400000:14400000)),regime=marketRegime(samples),stockSignal=signalFor(samples),signal=q.asset_class==='crypto'?(samples.length>=20&&regime.kind==='uptrend'&&regime.momentum_pct>=.8?'buy':'hold'):stockSignal,spread=Number.isFinite(q.ask)&&Number.isFinite(q.bid)&&q.ask>0?(q.ask-q.bid)/q.ask:Infinity,position=snapshot.positions.find(p=>compactSymbol(p.symbol)===compactSymbol(q.symbol)),marketAvailable=q.asset_class==='crypto'||clock.is_open;
  const gates={ATLAS:fresh(q,at)&&(q.source_health||0)>=80,ORION:marketAvailable&&samples.length>=(q.asset_class==='crypto'?20:16)&&signal==='buy',TITAN:spread<=(q.asset_class==='crypto'?.003:.005)&&regime.kind!=='high_volatility',NOVA:!openSymbols.has(compactSymbol(q.symbol)),VEGA:!position&&snapshot.positions.length<state.config.max_positions,LUNA:!state.halted&&!dailyBreached&&sharedRisk(state,snapshot,at).stale_positions===0&&sharedRisk(state,snapshot,at).exposure_remaining>0};
  const consensus=Math.round(Object.values(gates).filter(Boolean).length/Object.keys(gates).length*100);if(consensus>=policy.min_consensus_score)candidates.push({q,signal,samples,gates,spread,regime,consensus})
 }
 if(!candidates.length)return{...base,status:'scanning',reason:clock.is_open?'No unanimous regime-qualified entry signal':'Stocks closed; no unanimous crypto entry signal',next_open:clock.next_open,evaluated:state.markets.filter(q=>['stocks','crypto'].includes(q.asset_class)).length};
 const candidate=candidates.sort((a,b)=>b.regime.confidence-a.regime.confidence)[0],risk=sharedRisk(state,snapshot,at),ticket=riskSizedTicket({equity:risk.risk_base,cash:Math.min(state.cash_cents/100,snapshot.account.cash),price:candidate.q.ask,stop_pct:policy.stop_loss_pct,confidence:candidate.regime.confidence,ticket_cap:risk.ticket_limit,exposure_remaining:risk.exposure_remaining});
 if(ticket<(candidate.q.asset_class==='crypto'?10:1))return{...base,status:'scanning',reason:'Risk-sized ticket is below the paper minimum',gates:candidate.gates,consensus_score:candidate.consensus,regime:candidate.regime};
 return{...base,status:'shadow',reason:'Entry signal recorded for evaluation; automatic entry execution is disabled',orders_submitted:0,signal:'buy',symbol:candidate.q.symbol,gates:candidate.gates,regime:candidate.regime,risk_sized_ticket:ticket,reference_price:candidate.q.ask,quote_at:candidate.q.quote_at||candidate.q.fetched_at};

}
export function normalizeSolana(data){return(data.pairs||[]).filter(p=>p.chainId==='solana'&&number(p.priceUsd)>0&&number(p.liquidity?.usd)>0).sort((a,b)=>(number(b.liquidity?.usd)||0)-(number(a.liquidity?.usd)||0)).slice(0,8).map(p=>({id:p.pairAddress,asset_class:'solana',symbol:p.baseToken?.symbol||'Unknown',contract:p.baseToken?.address,price:number(p.priceUsd),liquidity_usd:number(p.liquidity?.usd),volume_h6:number(p.volume?.h6),volume_h24:number(p.volume?.h24),change_h1:number(p.priceChange?.h1),venue:p.dexId,source:'DexScreener',holders:null,concentration_verified:false,execution:'not_connected'}))}
export function normalizePrediction(data){if(!Array.isArray(data))throw new Error('Unexpected market response');return data.filter(m=>m.active&&!m.closed&&m.acceptingOrders===true).slice(0,8).map(m=>{let outcomes,prices;try{outcomes=typeof m.outcomes==='string'?JSON.parse(m.outcomes):m.outcomes;prices=typeof m.outcomePrices==='string'?JSON.parse(m.outcomePrices):m.outcomePrices}catch{return null}if(!Array.isArray(outcomes)||!Array.isArray(prices))return null;const ix=outcomes.findIndex(o=>String(o).toLowerCase()==='yes');if(ix<0)return null;const ask=number(m.bestAsk),bid=number(m.bestBid),prob=number(prices[ix]);if(prob===null||prob<0||prob>1)return null;return{id:String(m.id),asset_class:'prediction',symbol:m.question,price:prob,yes_bid:bid,yes_ask:ask,spread:ask!==null&&bid!==null?ask-bid:null,liquidity_usd:number(m.liquidityNum),volume_h24:number(m.volume24hr),closes_at:m.endDate,venue:'Polymarket',source:'Polymarket Gamma',execution:'not_connected',estimated_probability:null}}).filter(Boolean)}
export function normalizeKalshi(data){if(!Array.isArray(data.markets))throw new Error('Unexpected Kalshi response');return data.markets.slice(0,8).map(m=>({id:m.ticker,asset_class:'prediction',symbol:m.title,price:number(m.last_price_dollars),yes_bid:number(m.yes_bid_dollars),yes_ask:number(m.yes_ask_dollars),volume_h24:number(m.volume_24h_fp),liquidity_usd:number(m.liquidity_dollars),closes_at:m.close_time,venue:'Kalshi',source:'Kalshi',execution:'not_connected',estimated_probability:null})).filter(m=>m.price!==null&&m.price>=0&&m.price<=1)}
export function normalizeTrackedPrediction(m){const base=normalizePrediction([{...m,active:true,closed:false,acceptingOrders:true}]);if(!base.length)return[];const q=base[0];q.accepting_orders=m.acceptingOrders===true&&!m.closed;q.resolved=m.closed===true&&m.umaResolutionStatus==='resolved'&&(q.price===0||q.price===1);return[q]}
function sourceHealth(value,now=Date.now()){const age=value.last_success_at?Math.max(0,now-Date.parse(value.last_success_at)):null;const base=value.status==='connected'?100:value.status==='empty'?72:value.status==='rate_limited'?Math.max(25,65-(value.rate_limit_attempts||1)*10):value.status==='needs_credentials'?0:20;return{...value,health_score:Math.max(0,Math.round(base-(age===null?0:Math.min(30,age/600000*5)))),data_age_seconds:age===null?null:Math.round(age/1000)}}
export async function source(key,url,normalizer,headers,previous=null){const now=Date.now(),fetched_at=new Date(now).toISOString(),cached=previous?.markets||[];if(previous?.retry_at&&Date.parse(previous.retry_at)>now)return sourceHealth({...previous,status:'rate_limited',markets:cached,cached:cached.length>0,error:'Rate limited. Automatic retry at '+previous.retry_at},now);try{const markets=normalizer(await fetchJson(url,headers));return sourceHealth({key,status:markets.length?'connected':'empty',fetched_at,last_success_at:markets.length?fetched_at:previous?.last_success_at||null,markets,error:markets.length?null:'The source returned no eligible markets.',rate_limit_attempts:0,retry_at:null,cached:false},now)}catch(e){if(e.http_status===429){const attempts=(previous?.rate_limit_attempts||0)+1;const delay=Math.min(3600000,300000*2**Math.min(attempts-1,4));const retry_at=new Date(Math.max(now+delay,Number.isFinite(e.retry_after)?e.retry_after:0)).toISOString();return sourceHealth({key,status:'rate_limited',fetched_at,last_success_at:previous?.last_success_at||previous?.fetched_at||null,markets:cached,cached:cached.length>0,http_status:429,rate_limit_attempts:attempts,retry_at,error:'Rate limited. Automatic retry at '+retry_at},now)}return sourceHealth({key,status:'unavailable',fetched_at,last_success_at:previous?.last_success_at||previous?.fetched_at||null,markets:cached,cached:cached.length>0,error:e.name==='TimeoutError'?'Source timed out':e.message},now)}}
export async function collectMarketDesk(env,positions=[],previousSources=[]){const prior=key=>previousSources.find(s=>s.key===key),headers={'APCA-API-KEY-ID':env.ALPACA_API_KEY,'APCA-API-SECRET-KEY':env.ALPACA_API_SECRET};const stockRequest=env.ALPACA_API_KEY&&env.ALPACA_API_SECRET?source('stocks','https://data.alpaca.markets/v2/stocks/quotes/latest?symbols='+STOCKS.join(',')+'&feed=iex',d=>Object.entries(d.quotes||{}).map(([symbol,q])=>({id:symbol,asset_class:'stocks',symbol,price:number(q.ap)>0&&number(q.bp)>0?(number(q.ap)+number(q.bp))/2:null,bid:number(q.bp),ask:number(q.ap),quote_at:q.t,venue:'Alpaca',source:'Alpaca IEX',execution:'paper_connected'})).filter(q=>q.price>0),headers,prior('stocks')):Promise.resolve(sourceHealth({key:'stocks',status:'needs_credentials',markets:[],fetched_at:null,last_success_at:null,error:'Connect an Alpaca data account, or configure your chosen brokerage.',cached:false}));const cryptoRequest=env.ALPACA_API_KEY&&env.ALPACA_API_SECRET?source('crypto','https://data.alpaca.markets/v1beta3/crypto/us/latest/quotes?symbols='+encodeURIComponent(CRYPTO.join(',')),d=>Object.entries(d.quotes||{}).map(([symbol,q])=>({id:symbol,asset_class:'crypto',symbol,price:number(q.ap)>0&&number(q.bp)>0?(number(q.ap)+number(q.bp))/2:null,bid:number(q.bp),ask:number(q.ap),quote_at:q.t,venue:'Alpaca',source:'Alpaca Crypto',execution:'paper_connected'})).filter(q=>q.price>0),headers,prior('crypto')):Promise.resolve(sourceHealth({key:'crypto',status:'needs_credentials',markets:[],fetched_at:null,last_success_at:null,error:'Connect an Alpaca data account.',cached:false}));const results=await Promise.all([source('solana',PUBLIC_SOURCES.solana,normalizeSolana,undefined,prior('solana')),source('polymarket',PUBLIC_SOURCES.prediction,normalizePrediction,undefined,prior('polymarket')),source('kalshi',PUBLIC_SOURCES.kalshi,normalizeKalshi,undefined,prior('kalshi')),stockRequest,cryptoRequest]);
 // Keep open positions priced even if they drop out of a source's discovery list.
 for(const position of positions){if(results.some(s=>s.markets.some(q=>q.venue+':'+q.id===position.market_id)))continue;const ix=position.market_id.indexOf(':');const venue=position.market_id.slice(0,ix),id=position.market_id.slice(ix+1);if(venue==='Polymarket'&&/^[0-9]+$/.test(id)){const tracked=await source('polymarket-position','https://gamma-api.polymarket.com/markets/'+id,d=>normalizeTrackedPrediction(d));const target=results.find(s=>s.key==='polymarket');target.markets.push(...tracked.markets)}else if(venue==='Kalshi'&&results.find(s=>s.key==='kalshi').status!=='rate_limited'&&/^[A-Z0-9_-]+$/.test(id)){const tracked=await source('kalshi-position','https://api.elections.kalshi.com/trade-api/v2/markets/'+id,d=>normalizeKalshi({markets:[d.market]}));results.find(s=>s.key==='kalshi').markets.push(...tracked.markets)}}
 return{mode:'monitoring',execution_enabled:false,generated_at:new Date().toISOString(),sources:results,markets:results.flatMap(s=>s.markets.map(m=>({...m,fetched_at:s.last_success_at||s.fetched_at,cached:Boolean(s.cached),source_health:s.health_score}))),agents:[{name:'ATLAS',role:'SCAN',status:'monitoring'},{name:'NOVA',role:'VET',status:'awaiting_chain_verification'},{name:'ORION',role:'RESEARCH',status:'not_connected'},{name:'TITAN',role:'BOOK',status:'awaiting_probability_model'},{name:'VEGA',role:'SIZE',status:'paper_engine_only'},{name:'LUNA',role:'RISK',status:'no_live_positions'}],account:{equity:null,pnl:null,positions:[],status:'not_connected'},engine:{status:'not_deployed',mode:'paper',note:'Continuous execution requires deployment of the separate engine service.'}}}

export function agentLabSummary(state,env={},now=Date.now()){
 const skills=agentSkillSummary(state,env.OPENAI_RESEARCH_MODEL||'gpt-4.1-mini',now),trials=researchTrialsSummary(state,now);
 return{skills,trials,specialists:[{name:'SAGE',role:'Forecast learning',kind:'programmed',status:skills.snapshot?.adaptive?'adapting':'collecting',reason:skills.snapshot?.adaptive?'Weights reflect past scored AI forecasts; each new round freezes them.':'Collecting per-agent forward outcomes; equal weights until each forecasting role has 20 scored predictions.'},{name:'AEGIS',role:'Cost and timing audit',kind:'programmed',status:trials.experiment?.status||'waiting',reason:'Tracks delayed, cost-adjusted paper probes against an equal-ticket benchmark; missing exit quotes remain visible.'}],provider_calls:0,orders_submitted:0};
}
export async function getDesk(env){
 if(!env.DB)return collectMarketDesk(env);
 let {state}=await readState(env.DB);const now=Date.now();
 const monitor=monitoringSummary(state,env,now),incident=state.alerts.some(a=>a.type==='monitoring_stalled'&&!a.resolved_at);
 if((monitor.status==='stalled'&&!incident)||(incident&&(monitor.status==='healthy'||!monitor.enabled))){const updated=await mutate(env.DB,s=>updateMonitoringHealth(s,env,now));state=updated.state;}
 const summary=accountSummary(state,now);
 const positions=summary.positions||[],exposure=positions.reduce((sum,p)=>sum+(Number.isFinite(p.mark)?p.mark:p.cost_cents/100),0),realized=state.ledger.filter(x=>x.side==='sell').map(x=>x.realized_pnl||0),fees=state.ledger.reduce((sum,x)=>sum+(x.fee||0),0),wins=realized.filter(x=>x>0),losses=realized.filter(x=>x<0),grossProfit=wins.reduce((a,b)=>a+b,0),grossLoss=Math.abs(losses.reduce((a,b)=>a+b,0));
 let peak=null,maxDrawdown=0;for(const point of state.history){if(!Number.isFinite(point.equity))continue;peak=peak===null?point.equity:Math.max(peak,point.equity);if(peak>0)maxDrawdown=Math.max(maxDrawdown,(peak-point.equity)/peak*100)}
 const equity=summary.equity||summary.cash||0,config=state.config,brokerPositions=state.broker?.positions||[],risk=sharedRisk(state,state.broker,now);
 const analytics={realized_pnl:realized.reduce((a,b)=>a+b,0),unrealized_pnl:positions.reduce((sum,p)=>sum+(Number.isFinite(p.pnl)?p.pnl:0),0),fees,closed_positions:realized.length,win_rate:realized.length?wins.length/realized.length*100:null,profit_factor:grossLoss?grossProfit/grossLoss:grossProfit?null:0,expectancy:realized.length?realized.reduce((a,b)=>a+b,0)/realized.length:null,max_drawdown_pct:maxDrawdown};
 const markets=state.markets.map(m=>{const age=Math.max(0,now-Date.parse(m.quote_at||m.fetched_at)),spread=Number.isFinite(m.ask)&&Number.isFinite(m.bid)&&m.ask>0?(m.ask-m.bid)/m.ask:Number.isFinite(m.yes_ask)&&Number.isFinite(m.yes_bid)&&m.yes_ask>0?(m.yes_ask-m.yes_bid)/m.yes_ask:null;const freshness=Math.max(0,100-age/90000*100),liquidity=Number.isFinite(m.liquidity_usd)?Math.min(100,Math.log10(Math.max(1,m.liquidity_usd))/7*100):50,spreadScore=spread===null?55:Math.max(0,100-spread*2000),quality_score=Math.round(freshness*.45+liquidity*.3+spreadScore*.25);return{...m,quality_score,quote_age_seconds:Math.round(age/1000),spread_pct:spread===null?null:spread*100,max_paper_ticket:Math.min(risk.ticket_limit,Number.isFinite(m.liquidity_usd)?m.liquidity_usd*.005:risk.ticket_limit),tradable_fresh:age<=90000&&!m.cached}});
 const broker=state.broker||{status:alpacaReady(env)?'awaiting_sync':'not_configured',paper_endpoint_locked:true,orders:[],positions:[]};
 const autonomy=state.autonomy||{enabled:env.AUTONOMOUS_PAPER_ENABLED==='true',status:'awaiting_cycle',reason:'Waiting for the next market cycle'};
 const policy=smartPolicy(state),brokerUnrealized=brokerPositions.reduce((sum,p)=>sum+(number(p.unrealized_pl)||0),0),totalPnl=analytics.realized_pnl+analytics.unrealized_pnl+brokerUnrealized;
 const brokerReport=brokerTradeReport(broker);analytics.broker_trades=brokerReport.trades;analytics.broker_gross_realized_pnl=brokerReport.gross_realized_pnl;analytics.broker_unrealized_pnl=brokerUnrealized;analytics.total_pnl=null;analytics.observed_pnl=brokerReport.gross_realized_pnl===null?null:totalPnl+brokerReport.gross_realized_pnl;analytics.broker_realized_pnl=null;analytics.pnl_note=brokerReport.note;analytics.total_return_pct=null;
 const recentSamples=id=>state.observations.filter(o=>o.market_id===id).slice(-30),regimes={};for(const quote of markets.filter(m=>['stocks','crypto'].includes(m.asset_class)))regimes[quote.symbol]=marketRegime(recentSamples(marketKey(quote)));
 broker.positions=(broker.positions||[]).map(p=>{const key=compactSymbol(p.symbol),plan=positionExitPlan(p,policy,state.position_meta?.[key],now);return{...p,smart_exit:plan,regime:regimes[p.symbol]||regimes[p.symbol?.includes('/')?p.symbol:p.symbol?.replace('USD','/USD')]||null}});
 risk.health=risk.stale_positions||risk.uncertain_pending?'blocked':broker.status==='unavailable'?'degraded':risk.exposure>risk.exposure_limit?'halted':'healthy';risk.utilization_pct=risk.exposure_limit?risk.exposure/risk.exposure_limit*100:0;
 autonomy.consensus_score=autonomy.gates?Math.round(Object.values(autonomy.gates).filter(Boolean).length/Object.keys(autonomy.gates).length*100):0;autonomy.policy=policy;autonomy.regimes=regimes;
 const agents=deskAgentCards({sources:state.sources,markets,broker,autonomy,risk},now);
 return{testing_readiness:testingReadiness(state,env,now),monitoring:monitoringSummary(state,env,now),agent_lab:agentLabSummary(state,env,now),wallet_connection:gmgnSummary(state,env),insights:{learning:learningScorecard(state,now),validation:state.last_evaluation||null,agents:agentTrace(state,now),performance:performanceReport(state,now),memory:env.MEMORY?await env.MEMORY.stats():{available:false},readiness:state.last_readiness||null},research:researchSummary(state,env),simulation:simulationSummary(state,now),learning:learningSummary(state),mode:'paper',execution_enabled:alpacaReady(env),generated_at:new Date(now).toISOString(),sources:state.sources,markets,broker,autonomy,shadow:shadowSummary(state,now),agents,account:summary,engine:{status:'connected',mode:'paper',running:state.running,halted:state.halted,halt_reason:state.halt_reason,last_tick:state.last_tick,note:alpacaReady(env)?('Monitoring and shadow analysis only; manual Alpaca Paper orders require sign-in.'):'Hosted persistent paper engine. Broker routing is disabled.'},paper:{fill_test:state.last_fill_test||null,config:state.config,risk,analytics,ledger:state.ledger.slice(0,100),decisions:state.decisions.slice(0,50),alerts:state.alerts.slice(0,100),history:state.history.slice(-300),replay:state.last_replay,observations:state.observations.length}};
}
async function jsonBody(request){if(!request.headers.get('content-type')?.includes('application/json'))throw Error('JSON content type required');const body=await request.text();if(body.length>1000000)throw Error('Request too large');const input=JSON.parse(body);if(!input||Array.isArray(input)||typeof input!=='object')throw Error('An object is required');return input}
function interactiveWriteAllowed(request){const origin=request.headers.get('Origin');return Boolean(request.headers.get('oai-authenticated-user-id'))&&(!origin||origin===new URL(request.url).origin)&&request.headers.get('sec-fetch-site')!=='cross-site'}
export async function routeApi(request,env){const path=new URL(request.url).pathname;
 const response=(data,status=200)=>Response.json(data,{status,headers:{'Cache-Control':'no-store'}});
 if(path==='/api/health')return response({status:'ok',mode:'paper',execution_enabled:alpacaReady(env),paper_endpoint_locked:true,database_configured:!!env.DB});
 try{
 if(path==='/api/testing-readiness'){if(request.method!=='GET')return response({error:'Method not allowed'},405);const{state}=await readState(env.DB);return response(testingReadiness(state,env));}
 if(path==='/api/agent-lab'){if(request.method!=='GET')return response({error:'Method not allowed'},405);const{state}=await readState(env.DB);return response(agentLabSummary(state,env));}
 if(path==='/api/agent-lab/control'){if(request.method!=='POST')return response({error:'Method not allowed'},405);if(!interactiveWriteAllowed(request))return response({error:'Sign in to control the paper experiment'},403);const input=await jsonBody(request),now=Date.now();const updated=await mutate(env.DB,s=>{if(input.action==='start'||input.action==='resume'){const setup=testingReadiness(s,env,now);if(setup.steps.some(step=>(['ai','market','monitoring','history'].includes(step.id)&&step.status!=='pass')||(input.action==='resume'&&step.id==='experiment'&&step.status==='blocked')))throw Error('Complete Testing setup before starting or resuming an agent experiment');}return researchTrialsControl(s,input,now);});return response({ok:true,...updated.result,agent_lab:agentLabSummary(updated.state,env,now)});}
 if(path==='/api/wallets'){
  if(request.method!=='GET')return response({error:'Method not allowed'},405);
  return response(await getWalletResearch(env));
 }
 if(['/api/wallets/connection','/api/wallets/discover','/api/wallets/analyze','/api/wallets/activity','/api/wallets/watch'].includes(path)){
  if(request.method!=='POST')return response({error:'Method not allowed'},405);
  if(!interactiveWriteAllowed(request))return response({error:'Sign in to manage wallet research'},403);
  const input=await jsonBody(request);
  const operation={'/api/wallets/connection':gmgnConnection,'/api/wallets/discover':gmgnDiscover,'/api/wallets/analyze':gmgnAnalyze,'/api/wallets/activity':gmgnActivity,'/api/wallets/watch':gmgnWatch}[path];
  return response(await operation(env,input));
 }
 if(path==='/api/memory'&&request.method==='GET'){if(!env.MEMORY)return response({error:'Searchable archive unavailable'},503);const u=new URL(request.url);return response({results:await env.MEMORY.search({q:u.searchParams.get('q')||'',agent:u.searchParams.get('agent')||'',kind:u.searchParams.get('kind')||''}),...await env.MEMORY.stats()})}
 if(path==='/api/desk'&&request.method==='GET')return response(await getDesk(env));
 if(path==='/api/export'&&request.method==='GET'){const{state}=await readState(env.DB);return new Response(JSON.stringify({exported_at:new Date().toISOString(),mode:'paper',account:accountSummary(state),ledger:state.ledger,decisions:state.decisions,history:state.history,observations:state.observations,config:state.config,simulation:state.simulation,learning:state.learning,research:state.research,readiness:state.last_readiness,validation:state.last_evaluation,agent_lab:agentLabSummary(state,env)},null,2),{headers:{'Content-Type':'application/json','Content-Disposition':'attachment; filename="dots-paper-ledger.json"','Cache-Control':'no-store'}})}
 if(['/api/evaluation','/api/readiness','/api/memory/sync','/api/tick','/api/fill-test','/api/control','/api/order','/api/replay','/api/simulation/control','/api/simulation/test','/api/research/run','/api/research/preview','/api/research/control','/api/research/connection'].includes(path)){
 if(request.method!=='POST')return response({error:'Method not allowed'},405);
 // /api/fill-test only records an isolated diagnostic; it cannot change account funds or orders.
 // /api/tick is a shared updater behind this owner-private Site's access boundary.
 // Interactive money-state changes require the platform's signed-in visitor identity.
 if(!['/api/tick','/api/fill-test','/api/simulation/test','/api/research/preview'].includes(path)&&!interactiveWriteAllowed(request))return response({error:'Sign in to this private Site to change paper account state'},403);
 const input=await jsonBody(request);
 if(path==='/api/evaluation'){const {state}=await readState(env.DB);const report=evaluationReport(state,input);await mutate(env.DB,s=>{s.last_evaluation=report;return null});return response(report)}
 if(path==='/api/readiness'){const {state}=await readState(env.DB);const report=readinessReport(state,env);await mutate(env.DB,s=>{s.last_readiness=report;return null});return response(report)}
 if(path==='/api/memory/sync'){const {state}=await readState(env.DB);return response(await syncMemory(env,state,true))}
 if(path==='/api/research/connection')return response(await saveResearchConnection(env,input));
 if(path==='/api/research/run')return response(await runResearch(env,{...input,mode:'ai'}));
 if(path==='/api/research/preview')return response(await runResearch(env,{...input,mode:'preview'}));
 if(path==='/api/research/control'){const updated=await mutate(env.DB,s=>researchControl(s,input,env));return response(updated.result)}
 if(path==='/api/simulation/control'){const updated=await mutate(env.DB,s=>simulationControl(s,input.action));return response(updated.result)}
 if(path==='/api/simulation/test'){const result=simulationDiagnostic();await mutate(env.DB,s=>{if(!s.simulation)simulationControl(s,'start');s.simulation.last_test=result;return result});return response(result)}
 if(path==='/api/fill-test'){const result=fillDiagnostic();const updated=await mutate(env.DB,s=>{s.last_fill_test=result;return result});return response(updated.result)}
 if(path==='/api/tick')return response(await refreshMonitoring(env,{actor:'browser'}));
 if(path==='/api/control'){if(alpacaReady(env)&&input.action==='settings'&&input.auto_stocks===true)throw Error('Automatic broker trading is disabled; Alpaca Paper orders require a manual proposal');if(input.action==='settings'&&input.initial_cash!==undefined){const {state:s}=await readState(env.DB);if((s.broker?.positions||[]).length||(s.broker?.orders||[]).length)throw Error('Desk base is fixed after broker activity')}const updated=await mutate(env.DB,s=>controls(s,input));return response(updated.result)}
 if(path==='/api/order'&&env.ALPACA_API_KEY&&env.ALPACA_API_SECRET&&String(input.market_id||'').startsWith('Alpaca:')){const fingerprint=JSON.stringify(input);const reserved=await mutate(env.DB,s=>{s.broker_requests=s.broker_requests||{};const existing=s.broker_requests[input.intent_id];if(existing){if(existing.fingerprint!==fingerprint)throw Error('Intent ID already used with a different request');return{existing:true,result:existing.result||{status:'pending',mode:'alpaca_paper'}}}if(s.tick_lease?.until>Date.now()||Object.values(s.broker_requests).some(r=>r.status==='pending'||r.status==='uncertain'))throw Error('Order or monitoring reconciliation is in progress');s.broker_requests[input.intent_id]={fingerprint,status:'pending',at:Date.now()};return{reserved:true}});if(!reserved.result.reserved)return response(reserved.result.result);try{const result=await submitAlpacaPaperOrder(env,reserved.state,input);let broker;try{broker=await alpacaSnapshot(env)}catch{broker=reserved.state.broker||null}await mutate(env.DB,s=>{s.broker_requests=s.broker_requests||{};s.broker_requests[input.intent_id]={fingerprint,status:'submitted',result,at:Date.now()};if(broker)s.broker=broker;s.alerts.unshift({id:crypto.randomUUID(),type:'broker_order',message:'Alpaca Paper '+result.side+' '+result.symbol+' · '+result.broker_status,at:Date.now(),ref:'VEGA',read:false});s.alerts=s.alerts.slice(0,500);return result});return response(result)}catch(error){await mutate(env.DB,s=>{s.broker_requests=s.broker_requests||{};s.broker_requests[input.intent_id]={fingerprint,status:error.submission_unknown?'uncertain':'failed',result:{status:error.submission_unknown?'uncertain':'rejected',mode:'alpaca_paper',reason:error.message},at:Date.now()};return null});throw error}}
 if(path==='/api/order'){const updated=await mutate(env.DB,s=>{if(input.side==='buy'){const risk=sharedRisk(s);if(s.tick_lease?.until>Date.now()||risk.stale_positions||risk.uncertain_pending||!risk.position_slots_remaining)throw Error('Entry blocked by shared risk checks');if(Number(input.dollars)>Math.min(risk.ticket_limit,risk.exposure_remaining))throw Error('Requested entry exceeds the shared desk budget')}return order(s,input)});return response(updated.result)}
 if(path==='/api/replay'){const{state}=await readState(env.DB);let samples=input.samples;if(!samples){if(typeof input.market_id!=='string')throw Error('Select a market for recorded replay');samples=state.observations.filter(x=>x.market_id===input.market_id)}const result=replay(samples,Number(input.initial_cash||1000));const updated=await mutate(env.DB,s=>{s.last_replay={...result,curve:result.curve.slice(-300),trades:result.trades.slice(-100),at:Date.now(),source:input.samples?'uploaded_csv':'recorded_quotes',market_id:input.market_id||null};return s.last_replay});return response(updated.result)}
 }
 return response({error:'Not found'},404);
 }catch(error){
  const message=(path.startsWith('/api/wallets')||path.startsWith('/api/agent-lab'))&&error instanceof SyntaxError?'Valid JSON object required':error.message||'Operation failed';
  return response({error:message},error.gmgn_code==='rate_limited'?429:400);
 }
}
export {autonomousPaperCycle};
