(() => {
 const node=(tag,text='',cls='')=>{const el=document.createElement(tag);el.textContent=text;if(cls)el.className=cls;return el;};
 const finite=(value,digits=3)=>Number.isFinite(value)?value.toFixed(digits):'Awaiting outcomes';
 const money=value=>Number.isFinite(value)?new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(value):'Awaiting marks';
 const when=value=>Number.isFinite(value)?new Date(value).toLocaleString():'Not recorded';
 let latest=null,pending=false;
 const panel=node('section','','panel agent-lab');panel.id='agent-lab';
 const head=node('div','','panel-head');head.append(node('h2','AGENT LAB / LEARNING & PAPER EXPERIMENTS'),node('span','EVIDENCE FIRST'));panel.append(head);
 panel.append(node('p','Measure recorded forecasts and test a fixed paper policy against a paired baseline. Scores describe observed evidence; they do not measure intelligence or establish future profit.','agent-lab-note'));
 const skillsRoot=node('div','','agent-lab-skills'),specialistsRoot=node('div','','agent-lab-specialists'),trialsRoot=node('div','','agent-lab-trials'),status=node('p','','agent-lab-status');status.setAttribute('role','status');panel.append(skillsRoot,specialistsRoot,trialsRoot,status);
 const mount=document.querySelector('#wallet-research')||document.querySelector('#research-room')||document.querySelector('.markets-panel');if(mount)mount.after(panel);else(document.querySelector('main')||document.body).append(panel);
 function wrap(table,label){const div=node('div','','agent-lab-table-scroll');div.tabIndex=0;div.setAttribute('role','region');div.setAttribute('aria-label',label);div.append(table);return div;}
 function metric(label,value){const cell=node('div','','agent-lab-metric');cell.append(node('small',label),node('strong',value));return cell;}
 function renderSkills(){skillsRoot.replaceChildren(node('h3','Six-agent forecast scorecard'));const skills=latest?.skills;if(!skills){skillsRoot.append(node('p','Waiting for recorded forecast evidence.','agent-lab-note'));return;}
  skillsRoot.append(node('p',`Model: ${skills.model||'Not recorded'} · scoring policy: ${skills.policy_version||'Not recorded'} · ${skills.records_retained??0} records retained${skills.record_limit?' / '+skills.record_limit+' record limit':''}.`,'agent-lab-note'));
  const table=node('table'),head=node('thead'),header=node('tr');for(const label of ['Agent','Scored forecasts','Brier error ↓','Neutral error','Skill vs neutral','Expired / abstained','Learned weight'])header.append(node('th',label));head.append(header);table.append(head);const body=node('tbody');
  for(const role of skills.roles||[]){const snapshot=skills.snapshot||{},count=snapshot.scored_counts?.[role.name]??role.scored??0,weight=snapshot.weights?.[role.name],riskReview=['VEGA','LUNA'].includes(role.name),eligible=!!snapshot.adaptive&&count>=(snapshot.min_scored??20),row=node('tr');row.append(node('th',role.name),node('td',String(role.scored??0)),node('td',finite(role.mean_brier)),node('td',finite(role.neutral_brier??.25)),node('td',Number.isFinite(role.brier_skill_pct)?role.brier_skill_pct.toFixed(1)+'%':'Awaiting outcomes'),node('td',`${role.expired??0} / ${role.abstained??0}`),node('td',riskReview?'Risk review · outside blend':eligible&&Number.isFinite(weight)?(weight*100).toFixed(1)+'%':'Not learned · needs support'));body.append(row);}
  table.append(body);skillsRoot.append(wrap(table,'Forecast scores by agent'),node('p',`Lower Brier error is better; a neutral 50% forecast has error 0.250. Positive skill indicates lower recorded error than neutral. Learned blend weights require at least ${skills.snapshot?.min_scored??20} scored forecasts each for ATLAS, ORION, TITAN, and NOVA. VEGA and LUNA remain risk reviewers outside the blend; model weights are not retrained.`,'agent-lab-note'));
  const details=node('details');details.append(node('summary','Calibration, forecast exclusions, and recent errors'));
  for(const role of skills.roles||[]){const item=node('article','','agent-lab-role');item.append(node('h4',role.name),node('p',`${role.total??0} issued · ${role.pending??0} pending · ${role.unchanged??0} unchanged prices · ${role.invalid??0} invalid records. Expired and abstained forecasts do not count as scored outcomes.`,'agent-lab-note'));const bins=node('ul');for(const bin of role.calibration||[])bins.append(node('li',`${bin.range}: ${bin.count} forecasts · mean prediction ${Number.isFinite(bin.mean_probability)?(bin.mean_probability*100).toFixed(1)+'%':'unavailable'} · observed upward moves ${Number.isFinite(bin.observed_up_rate)?(bin.observed_up_rate*100).toFixed(1)+'%':'unavailable'} · ${bin.sufficient_support?'preliminary support':'fewer than 20 samples'}`));item.append(bins);for(const error of role.recent_errors||[])item.append(node('p',`${error.symbol||'Market'} · issued ${when(error.issued_at)} · Brier ${finite(error.brier)} · forecast up ${Number.isFinite(error.forecast_up)?(error.forecast_up*100).toFixed(1)+'%':'unavailable'} · observed ${error.actual??'unavailable'}`,'agent-lab-note'));details.append(item);}
  skillsRoot.append(details,node('p',skills.scope||'Forecast evidence is preliminary, correlated, and limited to recorded market observations.','agent-lab-note'));
 }
 function renderSpecialists(){specialistsRoot.replaceChildren();for(const specialist of latest?.specialists||[]){const card=node('article','','agent-lab-specialist');card.append(node('h3',specialist.name+' · '+specialist.role),node('b','PROGRAMMED SPECIALIST · NO EXTRA AI CALL'),node('p',specialist.reason||'Uses existing recorded evidence.','agent-lab-note'));specialistsRoot.append(card);}}
 function button(label,action){const b=node('button',label);b.type='button';b.disabled=pending||!latest;b.dataset.agentLabAction=action;b.onclick=()=>control(action);return b;}
 function renderTrials(){trialsRoot.replaceChildren(node('h3','Isolated AI forecast paper experiment'));const trials=latest?.trials,experiment=trials?.experiment,metrics=trials?.metrics||{},settings=experiment?.settings||{};
  const controls=node('div','','agent-lab-controls'),start=button(experiment?'Start new experiment':'Start experiment','start');if(experiment&&(experiment.status!=='paused'||(metrics.waiting??0)>0||(metrics.open??0)>0)){start.disabled=true;start.title='Pause the current experiment and let open pairs finish before starting a new one.';}controls.append(start);if(experiment?.status==='running')controls.append(button('Pause experiment','pause'));if(experiment?.status==='paused')controls.append(button('Resume experiment','resume'));trialsRoot.append(controls);
  trialsRoot.append(node('p',experiment?`Experiment ${experiment.status} · started ${when(experiment.started_at)} · policy ${experiment.policy_version||'Not recorded'}.`:'No experiment started. Starting freezes a fixed policy and waits for new eligible AI forecasts; it does not import older reports.','agent-lab-note'));
  const next=node('p','','agent-lab-note'),room=node('a','Research Room');room.href='#research-room';next.append(document.createTextNode('Start an experiment, then open '),room,document.createTextNode(' to run an AI round with your connected OpenAI API key. New results are scored when later market quotes arrive. GMGN is not required.'));trialsRoot.append(next);
  trialsRoot.append(node('p',`Fixed policy: forecast UP threshold ${Math.round((settings.long_threshold??.6)*100)}%; $${settings.ticket_usd??60} ticket; ${settings.fee_pct??.1}% fees per side; ${settings.slippage_bps??10} basis points adverse slippage; ${settings.entry_delay_seconds??15}-second entry delay; ${settings.holding_minutes??60}-minute hold. Every eligible forecast has a matched always-long benchmark.`,'agent-lab-note'));
  const counts=node('div','','agent-lab-metrics');for(const [label,value]of [['Registered forecasts',metrics.registered??0],['Pending entries',metrics.waiting??0],['Open pairs',metrics.open??0],['Closed pairs',metrics.closed_pairs??0],['Expired entries',metrics.expired??0],['Cancelled / skipped',`${metrics.cancelled??0} / ${metrics.skipped??0}`]])counts.append(metric(label,String(value)));trialsRoot.append(counts);
  if((metrics.closed_pairs??0)>0){const scores=node('div','','agent-lab-metrics');for(const [label,value]of [['Realized paper policy net P&L',money(metrics.policy_net_pnl)],['Realized paired benchmark net P&L',money(metrics.benchmark_net_pnl)],['Policy minus benchmark net',money(metrics.paired_net_advantage)]])scores.append(metric(label,value));trialsRoot.append(scores,node('p','Observed realized totals after modeled costs across isolated $60 probes. These are not portfolio returns or independently verified broker performance.','agent-lab-note'));}
  if(trials?.evidence_status==='preliminary')trialsRoot.append(node('p','The experiment has preliminary paired evidence. A positive result does not establish dependable profitability.','agent-lab-note'));
  else trialsRoot.append(node('p',`Insufficient paired evidence: ${metrics.closed_pairs??0}/${trials?.min_closed_pairs??30} closed pairs before a preliminary comparison. Any observed gains or losses above remain visible; more later observations are needed to assess the policy.`,'agent-lab-note'));
  if(metrics.unpriced_open)trialsRoot.append(node('p',metrics.unpriced_open+' open pairs have unavailable marks; incomplete marks limit performance comparisons.','agent-lab-note'));
  if(metrics.overdue_open)trialsRoot.append(node('p',metrics.overdue_open+' pairs are past the planned hold and waiting for an eligible exit quote.','agent-lab-note'));
  if(metrics.costs){const costs=node('details');costs.append(node('summary','Modeled costs and observation coverage'),node('pre',JSON.stringify({costs:metrics.costs,coverage:metrics.coverage},null,2)));trialsRoot.append(costs);}
  trialsRoot.append(node('p','All entries and exits are isolated virtual records. These controls submit no broker orders and make no additional AI calls. Existing research provider charges still apply when AI research is separately enabled. Pausing cancels pending entries; existing open positions continue their exit checks.','agent-lab-note'));
  if(trials?.probes?.length){const details=node('details');details.append(node('summary','Recent paired experiment records'),node('pre',JSON.stringify(trials.probes.slice(0,20),null,2)));trialsRoot.append(details);}
 }
 function render(){renderSkills();renderSpecialists();renderTrials();}
 async function control(action){if(pending||!latest)return;pending=true;for(const b of panel.querySelectorAll('[data-agent-lab-action]'))b.disabled=true;status.textContent='Saving paper experiment controls…';try{const response=await fetch('/api/agent-lab/control',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action})}),value=await response.json();if(!response.ok)throw Error(value.error||'Could not update the paper experiment.');latest=value.agent_lab||((value.skills&&value.trials)?value:{...latest,trials:value});status.textContent=action==='pause'?'Experiment paused. Pending entries are cancelled; open exits remain monitored.':action==='resume'?'Experiment resumed under its frozen policy. No orders or new AI calls were submitted.':'New isolated paper experiment started. It waits for new eligible forecasts.';}catch(error){status.textContent=error.message;}finally{pending=false;render();}}
 window.addEventListener('desk-data',event=>{if(event.detail?.agent_lab){latest=event.detail.agent_lab;render();}});
 if(window.dotsDeskData?.agent_lab)latest=window.dotsDeskData.agent_lab;render();
})();
