(()=>{
 const $=s=>document.querySelector(s),money=v=>v===null||v===undefined?'—':new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:2}).format(v),stamp=v=>v?new Date(v).toLocaleString():'—';
 async function closePosition(symbol,button){button.disabled=true;button.textContent='SUBMITTING…';try{const response=await window.withAgentActivity(['NOVA','VEGA','LUNA'],()=>fetch('/api/order',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({intent_id:crypto.randomUUID(),market_id:'Alpaca:'+symbol,side:'sell'})}));const value=await response.json();if(!response.ok)throw Error(value.error||'Order failed');button.textContent='SUBMITTED · '+value.broker_status;window.dispatchEvent(new Event('desk-refresh'))}catch(error){button.disabled=false;button.textContent='CLOSE IN ALPACA PAPER';const status=$('#broker-status');if(status)status.textContent=error.message}}
 function ensure(){if($('#broker-panel'))return;const panel=document.createElement('section');panel.id='broker-panel';panel.className='panel broker-panel';panel.innerHTML='<div class="panel-head"><h2>ALPACA PAPER BROKER</h2><span id="broker-status">AWAITING SYNC</span></div><div id="broker-account" class="metric-grid"></div><div class="broker-columns"><div><h3>POSITIONS</h3><div id="broker-positions" class="records-list"></div></div><div><h3>RECENT ORDERS</h3><div id="broker-orders" class="records-list"></div></div></div>';const anchor=$('#intelligence-grid')||$('.markets-panel');anchor.before(panel)}
 function metric(label,value){const el=document.createElement('div');el.className='metric';el.innerHTML='<small>'+label+'</small><strong>'+value+'</strong>';return el}
 function record(title,detail){const el=document.createElement('div');el.className='record';const b=document.createElement('b'),small=document.createElement('small');b.textContent=title;small.textContent=detail;el.append(b,small);return el}
 window.addEventListener('desk-data',event=>{ensure();const data=event.detail,broker=data.broker||{},account=broker.account||{};$('#broker-status').textContent=(broker.status||'not configured').replaceAll('_',' ').toUpperCase()+' · PAPER ONLY';$('#broker-account').replaceChildren(metric('PAPER EQUITY',money(account.equity)),metric('PAPER CASH',money(account.cash)),metric('BUYING POWER',money(account.buying_power)),metric('ROUTING',data.execution_enabled?'PAPER ORDERS ON':'OFF'));const positions=(broker.positions||[]).map(p=>{const x=p.smart_exit||{},levels=[x.stop_price?'stop '+money(x.stop_price):'',x.target_price?'target '+money(x.target_price):'',x.trailing_price?'trail '+money(x.trailing_price):''].filter(Boolean).join(' · '),el=record(p.side.toUpperCase()+' '+p.symbol,p.qty+' units · '+money(p.market_value)+' · P&L '+money(p.unrealized_pl)+' · '+String(x.action||'hold').toUpperCase()+(levels?' · '+levels:''));const note=document.createElement('small');note.textContent='Smart exit: '+(x.reason||'awaiting marks')+(p.regime?' · regime '+String(p.regime.kind).replaceAll('_',' '):'');const button=document.createElement('button');button.className='inline-button';button.textContent='CLOSE IN ALPACA PAPER';button.addEventListener('click',()=>closePosition(p.symbol,button));el.append(note,button);return el});$('#broker-positions').replaceChildren(...positions);if(!positions.length)$('#broker-positions').textContent='No Alpaca Paper positions.';const orders=(broker.orders||[]).slice(0,20).map(o=>record(o.side.toUpperCase()+' '+o.symbol+' · '+o.status,(o.filled_qty||0)+' / '+(o.qty||0)+' units · avg '+money(o.filled_avg_price)+' · '+stamp(o.submitted_at)));$('#broker-orders').replaceChildren(...orders);if(!orders.length)$('#broker-orders').textContent='No Alpaca Paper orders yet.';document.querySelectorAll('.header-stat').forEach(stat=>{if(stat.querySelector('small')?.textContent.includes('LIVE ORDERS')){stat.querySelector('small').textContent='PAPER BROKER';stat.querySelector('b').textContent=data.execution_enabled?'ON':'OFF'}});const footer=$('#footer-status');if(footer)footer.textContent='ALPACA PAPER ROUTING · LIVE MONEY DISABLED'});
 window.addEventListener('desk-data',event=>{const data=event.detail,a=data.autonomy||{},panel=$('#broker-panel');if(!panel)return;let box=$('#autonomy-consensus');if(!box){box=document.createElement('div');box.id='autonomy-consensus';box.className='autonomy-consensus';panel.querySelector('.broker-columns').before(box)}const gates=a.gates||{};box.replaceChildren();const title=document.createElement('b');title.textContent='DETERMINISTIC CHECKS · '+String(a.status||'awaiting cycle').replaceAll('_',' ').toUpperCase();const reason=document.createElement('span');reason.textContent=a.reason||'Waiting for the next cycle';const agents=document.createElement('small');agents.textContent=['ATLAS','ORION','TITAN','NOVA','VEGA','LUNA'].map(name=>name+' '+(gates[name]===true?'✓':gates[name]===false?'×':'·')).join('   ');box.append(title,reason,agents)});
})();
