(() => {
 let latest=null,monitoring=null,busy=false,awaitingTargetRefresh=false,expectedTarget=null;
 const dirty=new Set();
 const node=(tag,text='',cls='')=>{const element=document.createElement(tag);element.textContent=text;if(cls)element.className=cls;return element;};
 const percent=(value,digits=2)=>Number.isFinite(value)?(value>0?'+':'')+value.toFixed(digits)+'%':'Not estimated';
 const duration=value=>Number.isFinite(value)?(value/60).toFixed(value<600?1:0)+' minutes':'Not observed';
 const historyReady=()=>latest?.market_evidence?.readiness?.ready===true&&!awaitingTargetRefresh;
 function currentTarget(){return document.querySelector('#research-room form')?.elements.target_symbol.value||null;}
 function targetSaved(){return currentTarget()===(latest?.target_symbol||null);}
 function updateControls(){const panel=document.querySelector('#research-room');if(!panel)return;const form=panel.querySelector('form');
  panel.querySelector('[data-preview]').disabled=busy;
  const ai=panel.querySelector('[data-ai]');ai.disabled=busy||!latest?.configured||!historyReady()||!targetSaved();ai.title=!latest?.configured?'Connect an OpenAI API key first.':!targetSaved()?'Save the selected market before running AI research.':!historyReady()?'Wait for sufficient fresh observed market history.':'';
  form.querySelector('[data-save]').disabled=busy;
  // A disconnected or unverified schedule can always be switched off.
  form.elements.enabled.disabled=busy||((!latest?.configured||!monitoring?.background_ready)&&!form.elements.enabled.checked);
 }
 async function run(mode){if(busy)return;const panel=document.querySelector('#research-room'),status=panel.querySelector('.research-action');
  if(mode==='ai'&&(!latest?.configured||!historyReady()||!targetSaved())){status.textContent='Connect AI, save the market selection, and collect ready market history before running this round.';return;}
  busy=true;updateControls();status.textContent=mode==='preview'?'Checking the free research workflow…':'Running six sequential AI reviews…';
  const input={intent_id:crypto.randomUUID(),scenario:panel.querySelector('textarea').value};const symbol=currentTarget();if(symbol)input.symbol=symbol;
  try{const result=await window.withAgentActivity(['ATLAS','ORION','TITAN','NOVA','VEGA','LUNA'],async()=>{const response=await fetch(mode==='preview'?'/api/research/preview':'/api/research/run',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(input)});const value=await response.json();if(!response.ok)throw Error(value.error||'Research request failed');return value;});status.textContent=(result.message||result.error||'Research '+result.status)+'. No order was submitted.';window.dispatchEvent(new Event('desk-refresh'));}
  catch(error){status.textContent=error.message;}finally{busy=false;updateControls();}
 }
 function ensurePanel(){let panel=document.querySelector('#research-room');if(panel)return panel;
  panel=node('section','','panel research-room');panel.id='research-room';const header=node('div','','panel-head');header.append(node('h2','SIX-AGENT RESEARCH ROOM'),node('span','OBSERVED HISTORY · FORECASTS · COSTS'));panel.append(header,node('p','','research-connection market-note'));
  const form=document.createElement('form');form.className='research-controls';
  const targetLabel=node('label','Research market: '),target=document.createElement('select');target.name='target_symbol';target.setAttribute('aria-label','Research market');targetLabel.style.flexWrap='wrap';targetLabel.style.maxWidth='100%';target.style.maxWidth='100%';targetLabel.append(target);form.append(targetLabel);
  const enabledLabel=node('label'),enable=document.createElement('input');enable.type='checkbox';enable.name='enabled';enabledLabel.append(enable,document.createTextNode(' Allow scheduled AI research (provider charges apply)'));form.append(enabledLabel);
  const capLabel=node('label','Maximum AI rounds per day: '),cap=document.createElement('select');cap.name='cap';for(const count of [1,2,3,4]){const option=node('option',String(count));option.value=count;cap.append(option);}capLabel.append(cap);form.append(capLabel);
  const save=node('button','SAVE RESEARCH SETTINGS');save.type='submit';save.dataset.save='';form.append(save);
  form.addEventListener('input',event=>{if(event.target.name)dirty.add(event.target.name);});
  target.addEventListener('change',()=>{updateControls();panel.querySelector('.research-market-selection').textContent=targetSaved()?'The saved market selection is used for new research rounds.':'Save this market selection to update its history checks before running an AI round.';});
  enable.addEventListener('change',()=>{if(enable.checked&&!monitoring?.background_ready){enable.checked=false;panel.querySelector('.research-action').textContent='Scheduled AI research requires verified VPS minute monitoring. Manual rounds can run from the visible hosted dashboard.';}updateControls();});
  form.onsubmit=async event=>{event.preventDefault();if(busy)return;busy=true;updateControls();const status=panel.querySelector('.research-action'),previousTarget=latest?.target_symbol||null,input={enabled:enable.checked,max_rounds_daily:Number(cap.value),target_symbol:target.value||null};
   status.textContent='Saving the research market and AI usage settings…';
   try{const response=await fetch('/api/research/control',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(input)}),value=await response.json();if(!response.ok)throw Error(value.error||'Could not save research settings');dirty.clear();awaitingTargetRefresh=input.target_symbol!==previousTarget;expectedTarget=input.target_symbol;latest={...latest,target_symbol:value.target_symbol??input.target_symbol,enabled:value.enabled,max_rounds_daily:value.max_rounds_daily};status.textContent=value.enabled?'Research settings saved. Scheduled AI requires verified VPS minute monitoring and stays within the daily cap.':'Research settings saved. Scheduled paid research is off; manual AI rounds remain separate.';panel.querySelector('.research-market-selection').textContent=awaitingTargetRefresh?'Market selection saved. Waiting for its refreshed history checks.':'The saved market selection is used for new research rounds.';window.dispatchEvent(new Event('desk-refresh'));}
   catch(error){status.textContent=error.message;}finally{busy=false;updateControls();}
  };panel.append(form,node('p','','research-market-selection market-note'),node('div','','research-market-evidence research-report'));
  const scenario=node('label','Hypothetical scenario to explore','research-scenario'),area=document.createElement('textarea');area.rows=3;area.maxLength=3000;area.placeholder='Example: How would a volatility spike challenge the current bullish case?';scenario.append(area);panel.append(scenario);
  const controls=node('div','','sim-controls'),preview=node('button','PREVIEW WORKFLOW · FREE'),ai=node('button','RUN AI RESEARCH');preview.type='button';preview.dataset.preview='';preview.onclick=()=>run('preview');ai.type='button';ai.dataset.ai='';ai.onclick=()=>run('ai');controls.append(preview,ai);panel.append(controls);
  const status=node('p','','research-action market-note');status.setAttribute('role','status');panel.append(status,node('div','','research-usage'),node('div','','research-reports'),node('p','','research-note market-note'));
  (document.querySelector('#simulation-panel')||document.querySelector('#learning-lab')||document.querySelector('.markets-panel')||document.querySelector('main')).after(panel);return panel;
 }
 function renderTarget(panel){const form=panel.querySelector('form'),select=form.elements.target_symbol,focused=document.activeElement===select;
  if(!focused){const desired=dirty.has('target_symbol')?select.value:(latest.target_symbol||''),targets=[...new Map((latest.market_evidence?.available_targets||[]).map(target=>[target.symbol,target])).values()];select.replaceChildren();const auto=node('option','Auto · available stock or crypto');auto.value='';select.append(auto);for(const target of targets){const option=node('option',target.symbol+' · '+target.asset_class);option.value=target.symbol;select.append(option);}if(desired&&!targets.some(target=>target.symbol===desired)){const option=node('option',desired+' · currently unavailable');option.value=desired;select.append(option);}select.value=desired;
  }
  if(document.activeElement!==form.elements.enabled&&!dirty.has('enabled'))form.elements.enabled.checked=latest.enabled;
  if(document.activeElement!==form.elements.cap&&!dirty.has('cap'))form.elements.cap.value=latest.max_rounds_daily;
  panel.querySelector('.research-market-selection').textContent=targetSaved()?'The saved market selection is used for new research rounds.':'Save this market selection to update its history checks before running an AI round.';
 }
 function renderEvidence(panel){const root=panel.querySelector('.research-market-evidence'),evidence=latest.market_evidence;root.replaceChildren(node('h3','Market evidence for the next round'));if(!evidence){root.append(node('p','Waiting for observed market evidence.'));return;}
  const coverage=evidence.history?.coverage||{},recent=coverage.recent_30m||{},readiness=evidence.readiness||{},features=evidence.features||{},costs=evidence.cost_model||{};
  root.append(node('p',`${evidence.selected?.symbol||'No supported market'} · ${readiness.ready?'history ready':'waiting for eligible history'} · ${recent.sample_count??0} distinct quotes in the last 30 minutes across ${duration(recent.span_seconds)} · largest recent source gap ${duration(recent.max_gap_seconds)}.`));
  root.append(node('p',`AI readiness requires at least ${readiness.minimum_distinct_quotes??12} distinct recent quotes across ${duration(readiness.minimum_span_seconds??600)}, with gaps no longer than ${duration(readiness.max_gap_seconds??300)}, plus a fresh uncached bid/ask book and spread at most ${readiness.max_spread_pct??.5}%. The server rechecks these conditions before paid calls.`));
  if(!readiness.ready&&readiness.reasons?.length){const reasons=node('ul');for(const reason of readiness.reasons)reasons.append(node('li',reason));root.append(reasons);}
  root.append(node('p',`Retained observed history: ${coverage.sample_count??0} distinct quotes across ${duration(coverage.span_seconds)}. Observed price move ${percent(features.observed_return_pct)}; descriptive trend ${percent(features.linear_trend_pct_per_hour)} per hour; sample return volatility ${percent(features.realized_sample_volatility_pct)}. Irregular observations are not regular time bars; these features are descriptive and are not forecasts.`));
  root.append(node('p',`Modeled round-trip break-even move: ${percent(costs.estimated_break_even_move_pct)}. Stressed round-trip cost: ${percent(costs.stressed_roundtrip_pct)}. Costs use ${costs.fee_pct_per_side??.1}% fees and ${costs.slippage_bps_per_side??10} bps slippage per side plus the observed spread; stress doubles each component. These assumptions do not verify broker fees or future spreads.`));
  if(features.market_hours)root.append(node('p','Market-hours context: '+features.market_hours.schedule+' · '+features.market_hours.note));
  root.append(node('p','Independent news and trade-volume evidence are unavailable. No news or volume is inferred from the recorded quotes.'));
 }
 function renderReports(panel){const reports=panel.querySelector('.research-reports');reports.replaceChildren();if(!latest.reports?.length)reports.append(node('p','No research rounds yet. Preview the workflow or finish the guided testing setup.'));
  for(const report of (latest.reports||[]).slice(0,3)){const article=node('article','','research-report');article.append(node('h3',(report.mode==='ai'?'AI RESEARCH':'PROGRAMMED WORKFLOW PREVIEW')+' · '+String(report.status||'waiting').toUpperCase()),node('p',new Date(report.at).toLocaleString()+' · '+(report.symbol||'No fresh quote')+' · no orders executed'));
   article.append(node('p',`Model ${report.model||'not recorded'} · context ${report.prompt_version||'legacy'} · skill ${report.agent_policy_version||'legacy'} · return policy ${report.forecast_policy_version||'legacy'}. Older versions remain visible and do not count toward current-version scores.`));
   if(report.scenario)article.append(node('p','Hypothetical scenario: '+report.scenario));
   const grid=node('div','','research-agents');for(const agent of report.agents||[]){const card=node('div','','research-agent');card.append(node('b',agent.name+' · '+String(agent.stance||'abstain').toUpperCase()),node('p',agent.summary||''),node('small','Expected one-hour gross move: '+percent(agent.expected_return_pct)+' · downside scenario: '+percent(agent.downside_return_pct)),node('small','Challenge: '+(agent.challenge||'')),node('small','Evidence: '+((agent.evidence_ids||[]).join(', ')||'None')),node('small','Missing: '+((agent.missing||[]).join('; ')||'None')));grid.append(card);}article.append(grid);
   if(report.error)article.append(node('p','Round failed: '+report.error));
   if(Number.isFinite(report.probability_up))article.append(node('p','Experimental advisory forecast UP: '+(report.probability_up*100).toFixed(1)+'%. Agent agreement is not independent validation.'));
   const forecast=report.return_forecast,costs=report.cost_summary;if(forecast){article.append(node('p',`Blended expected one-hour gross move ${percent(forecast.expected_return_pct)} · downside scenario ${percent(forecast.downside_return_pct)} · expected move minus base modeled costs ${percent(forecast.estimated_net_return_pct)}. These are unverified forecasts; downside is not a guaranteed loss bound.`));if(costs)article.append(node('p',`Frozen modeled round-trip break-even cost ${percent(costs.round_trip_cost_pct)} · stressed cost ${percent(costs.stressed_round_trip_cost_pct)}. Paper fills and realized costs are measured separately in Agent lab.`));}
   if(report.outcome){const outcome=report.outcome;article.append(node('p','Future-price evaluation: '+outcome.status+(Number.isFinite(outcome.brier)?' · observed '+outcome.direction+' · Brier '+outcome.brier.toFixed(4):'')+(Number.isFinite(outcome.return_pct)?' · observed gross move '+percent(outcome.return_pct):'')+(Number.isFinite(outcome.return_error?.absolute_error_pct)?' · absolute return error '+outcome.return_error.absolute_error_pct.toFixed(2)+' percentage points':'')));}
   else if(report.mode==='ai'&&report.status==='completed')article.append(node('p','Waiting for fresh quotes near '+new Date(report.due_at).toLocaleTimeString()+' to evaluate the one-hour forecast.'));
   reports.append(article);
  }
 }
 function renderData(data){const lab=data?.research;if(!lab)return;monitoring=data.testing_readiness?.monitoring||data.monitoring||null;if(awaitingTargetRefresh&&(lab.target_symbol||null)!==expectedTarget){updateControls();return;}latest=lab;awaitingTargetRefresh=false;const panel=ensurePanel();
  panel.querySelector('.research-connection').textContent=lab.configured?'AI provider configured · '+lab.provider+' / '+lab.model+' · scheduled research '+(lab.enabled?'enabled':'off'):'AI NOT CONNECTED. Open API SETUP to securely connect an OpenAI API key, or copy an evidence packet for manual review using your ChatGPT subscription. The free preview uses no AI API.';
  renderTarget(panel);renderEvidence(panel);updateControls();
  const usage=panel.querySelector('.research-usage');usage.replaceChildren();for(const [label,value]of [['AI ROUNDS TODAY',(lab.usage_today?.rounds??0)+'/'+lab.max_rounds_daily],['REPORTED TOKENS',String(lab.usage_today?.tokens??0)],['CURRENT-VERSION SCORED',String(lab.evaluated??0)],['CURRENT-VERSION BRIER',Number.isFinite(lab.mean_brier)?lab.mean_brier.toFixed(4):'Awaiting outcomes']]){const box=node('div','','metric');box.append(node('small',label),node('strong',value));usage.append(box);}
  renderReports(panel);
  panel.querySelector('.research-note').textContent=(lab.note||'')+' Scores above use the current model and context/skill/return-policy versions: '+(lab.prompt_version||lab.versions?.prompt||'not recorded')+' / '+(lab.agent_policy_version||lab.versions?.skill||'not recorded')+' / '+(lab.forecast_policy_version||lab.versions?.forecast||'not recorded')+'. Daily limits reset at midnight in Europe/Stockholm. Scheduled AI requires verified VPS minute monitoring and runs at most hourly within the selected daily cap. The hosted visible dashboard supports manual AI rounds; browser polling does not enable scheduled paid research. Memory stores recent reports and observed outcomes; model weights are not retrained.';
 }
 window.addEventListener('desk-data',event=>renderData(event.detail));if(window.dotsDeskData)renderData(window.dotsDeskData);
})();
