// Subscription-friendly review: exports evidence for this chat; never calls a model or broker.
(()=>{
 const money=v=>Number.isFinite(v)?new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(v):'Not reconciled';
 let latest;
 function row(title,body){const el=document.createElement('div');el.className='record';const b=document.createElement('b'),p=document.createElement('small');b.textContent=title;p.textContent=body;el.append(b,p);return el}
 window.addEventListener('desk-data',({detail:d})=>{
  latest=d;let panel=document.getElementById('shadow-review');
  if(!panel){panel=document.createElement('section');panel.id='shadow-review';panel.className='panel';panel.style.padding='24px';const heading=document.createElement('h2');heading.textContent='Shadow research & trade review';const note=document.createElement('p');note.textContent='These programmed shadow checks use no AI API. Model-powered reviews, if configured, appear in the separate Research Room. Broker entries require manual approval. Exit conditions create review alerts.';const button=document.createElement('button');button.textContent='Prepare review for ChatGPT';const output=document.createElement('textarea');output.id='chat-review';output.hidden=true;output.rows=12;output.style.width='100%';output.setAttribute('aria-label','Evidence packet to copy into ChatGPT');button.onclick=()=>{output.hidden=false;output.value=JSON.stringify({instruction:'Review this paper desk evidence. Identify risks, missing data and reasons not to trade. Do not invent news, prices or profitability. Do not execute orders.',as_of:latest.generated_at,broker_as_of:latest.broker?.synced_at,risk:latest.paper?.risk,positions:latest.broker?.positions,orders:latest.broker?.orders,performance:latest.paper?.analytics,analysis:latest.shadow,source_health:latest.sources?.map(s=>({source:s.key,status:s.status,as_of:s.last_success_at}))},null,2);output.focus();output.select()};const records=document.createElement('div');records.id='shadow-records';records.className='records-list';panel.append(heading,note,button,output,records);document.querySelector('.markets-panel').before(panel)}
  const s=d.shadow||{},root=document.getElementById('shadow-records');root.replaceChildren(row('Validation status',`${s.evaluated||0} evaluated shadow observations. No demonstrated trading edge. A rule-agreement score is not a probability of profit.`),row('Risk budget',`${money(d.paper?.risk?.risk_base)} desk base · ${money(d.paper?.risk?.reserved_exposure)} reserved for pending entries`));
  for(const r of s.reviews||[])root.append(row(`${r.symbol} · ${new Date(r.at).toLocaleString()} · NOT EXECUTED`,`${money(r.dollars)} hypothetical ticket. ${r.outcome?.status==='evaluated'?r.outcome.modeled_return_pct.toFixed(2)+'% modeled return after costs over '+Math.round(r.outcome.horizon_minutes)+' minutes':r.outcome?.status==='missed_window'?'Evaluation window missed':'Awaiting future observation'}. ${(r.challenge||[]).join('; ')}`));
  for(const t of d.paper?.analytics?.broker_trades||[])root.append(row(t.symbol+' closed broker fill',money(t.gross_pnl)+' gross · net P&L and fees unverified · '+t.status));
  const a=d.paper?.analytics,stats=document.querySelectorAll('.stats article');if(a&&stats[1]){stats[1].querySelector('label').textContent='OBSERVED PAPER P&L';stats[1].querySelector('strong').textContent=money(a.observed_pnl);stats[1].querySelector('small').textContent='Includes matched gross broker fills; fees unverified'}
 });
})();
