(()=>{
 const $=s=>document.querySelector(s);
 const money=v=>v===null||v===undefined||!Number.isFinite(Number(v))?'—':new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:2}).format(v);
 const pct=v=>v===null||v===undefined||!Number.isFinite(Number(v))?'—':Number(v).toFixed(1)+'%';
 const compact=v=>v===null||v===undefined||!Number.isFinite(Number(v))?'—':new Intl.NumberFormat('en-US',{notation:'compact',maximumFractionDigits:1}).format(v);
 const ago=seconds=>seconds===null||seconds===undefined?'No successful update':seconds<60?seconds+'s old':Math.round(seconds/60)+'m old';
 function ensurePanel(){if($('#intelligence-grid'))return;const section=document.createElement('section');section.id='intelligence-grid';section.className='intelligence-grid';section.innerHTML=`<article class="panel intelligence-card"><div class="panel-head"><h2>RISK HEADROOM</h2><span>SERVER ENFORCED</span></div><div id="risk-headroom" class="metric-grid"></div></article><article class="panel intelligence-card"><div class="panel-head"><h2>PERFORMANCE QUALITY</h2><span>OBSERVED PAPER RESULTS</span></div><div id="performance-quality" class="metric-grid"></div></article><article class="panel intelligence-card wide"><div class="panel-head"><h2>SMART SAFETY</h2><span>EXIT PLAN · PORTFOLIO GUARDS</span></div><div id="smart-safety" class="decision-grid"></div></article><article class="panel intelligence-card wide"><div class="panel-head"><h2>MARKET REGIMES</h2><span>TREND · RANGE · VOLATILITY</span></div><div id="market-regimes" class="decision-grid"></div></article><article class="panel intelligence-card wide"><div class="panel-head"><h2>SOURCE HEALTH</h2><span>LAST-GOOD DATA + INCIDENTS</span></div><div id="source-health-grid" class="health-grid"></div></article><article class="panel intelligence-card wide"><div class="panel-head"><h2>DECISION QUALITY</h2><span>FRESHNESS · SPREAD · LIQUIDITY</span></div><div id="decision-quality" class="decision-grid"></div></article>`;$('.markets-panel').before(section)}
 function metric(label,value,note=''){const el=document.createElement('div');el.className='metric';el.innerHTML=`<small>${label}</small><strong>${value}</strong><span>${note}</span>`;return el}
 function renderRisk(data){const r=data.paper?.risk,c=data.paper?.config;if(!r||!c)return;$('#risk-headroom').replaceChildren(metric('EXPOSURE USED',pct(r.exposure_pct),money(r.exposure)+' of '+money(r.exposure_limit)),metric('ROOM REMAINING',money(r.exposure_remaining),'Across all positions'),metric('NEXT TICKET CAP',money(r.ticket_limit),c.ticket_pct+'% of free cash'),metric('POSITION SLOTS',String(r.position_slots_remaining),c.max_positions+' maximum'),metric('QUOTE COVERAGE',r.stale_positions?'<span class="warn">'+r.stale_positions+' STALE</span>':r.fresh_positions+' FRESH','Open positions only'),metric('DAILY LOSS STOP',pct(c.daily_loss_pct),'Hard halt threshold'))}
 function renderAnalytics(data){const a=data.paper?.analytics;if(!a)return;$('#performance-quality').replaceChildren(metric('OBSERVED P&L',money(a.observed_pnl),'Matched gross fills; broker fees unverified'),metric('BROKER UNREALIZED',money(a.broker_unrealized_pnl),'Open broker positions'),metric('BROKER GROSS REALIZED',money(a.broker_gross_realized_pnl),'Before fees and quantity deductions'),metric('WIN RATE',pct(a.win_rate),a.closed_positions+' internally closed'),metric('EXPECTANCY',money(a.expectancy),'Per closed internal position'),metric('INTERNAL DRAWDOWN',pct(a.max_drawdown_pct),'Recorded desk equity'))}
 function renderSafety(data){const root=$('#smart-safety'),r=data.paper?.risk,a=data.autonomy||{},positions=data.broker?.positions||[];const cards=[metric('RISK HEALTH',String(r?.health||'unknown').toUpperCase(),pct(r?.utilization_pct)+' of exposure budget'),metric('RULE AGREEMENT',pct(a.consensus_score),a.reason||'Waiting for evaluation'),metric('SHADOW RISK',pct(a.policy?.risk_per_trade_pct),'Maximum equity risk per new paper trade')];for(const p of positions){const x=p.smart_exit||{};cards.push(metric(p.symbol+' EXIT',String(x.action||'hold').toUpperCase(),(x.reason||'Waiting')+(x.pnl_pct===null?'':' · '+pct(x.pnl_pct))))}root.replaceChildren(...cards)}
 function renderRegimes(data){const root=$('#market-regimes'),items=Object.entries(data.autonomy?.regimes||{});root.replaceChildren(...items.map(([symbol,r])=>metric(symbol,String(r.kind||'unknown').replaceAll('_',' ').toUpperCase(),pct(r.momentum_pct)+' momentum · '+pct(r.volatility_pct)+' volatility · '+(r.confidence||0)+'/100 heuristic trend score')));if(!items.length)root.textContent='Collecting enough observations to classify market conditions.'}
 function renderSources(data){$('#source-health-grid').replaceChildren(...(data.sources||[]).map(s=>{const el=document.createElement('div');el.className='health-card '+s.status;const retry=s.retry_at?' · retry '+new Date(s.retry_at).toLocaleTimeString():'';el.innerHTML=`<div><b>${s.key.toUpperCase()}</b><span>${s.status.replaceAll('_',' ')}</span></div><strong>${s.health_score??0}</strong><small>${ago(s.data_age_seconds)}${s.cached?' · cached quotes':''}${retry}</small>`;return el}));document.querySelectorAll('#source-status .source-box').forEach((box,i)=>{const s=data.sources[i];if(!s)return;const note=box.querySelector('small');if(note&&s.status==='rate_limited')note.textContent=(s.cached?'Showing last-good quotes. ':'No cached quotes. ')+'Retrying at '+new Date(s.retry_at).toLocaleTimeString();if(s.cached)box.classList.add('cached')})}
 function renderDecisions(data){const root=$('#decision-quality'),markets=(data.markets||[]).slice().sort((a,b)=>(b.quality_score||0)-(a.quality_score||0)).slice(0,6);root.replaceChildren(...markets.map(m=>{const el=document.createElement('div');el.className='decision-card';const prediction=m.asset_class==='prediction',breakEven=prediction?Math.min(1,(m.yes_ask??m.price)*1.02):null,head=document.createElement('div'),title=document.createElement('b'),score=document.createElement('strong'),detail=document.createElement('p'),note=document.createElement('small');title.textContent=m.symbol;score.textContent=(m.quality_score??0)+'/100';detail.textContent=m.venue+' · '+(m.cached?'STALE CACHE':(m.quote_age_seconds??0)+'s old')+' · '+(m.spread_pct===null?'spread unavailable':pct(m.spread_pct)+' spread');note.textContent='Liquidity '+compact(m.liquidity_usd)+' · paper cap '+money(m.max_paper_ticket)+(prediction?' · break-even ≈ '+pct(breakEven*100):'');head.append(title,score);el.append(head,detail,note);return el}));if(!markets.length)root.textContent='No market quotes are available for quality scoring.'}
 function renderReplay(data){const r=data.paper?.replay;if(!r)return;const panel=$('#replay-result');let extra=panel.querySelector('.replay-smart');if(!extra){extra=document.createElement('div');extra.className='replay-smart metric-grid';panel.prepend(extra)}extra.replaceChildren(metric('BUY/HOLD BENCHMARK',money(r.benchmark_buy_hold_pnl)),metric('EXCESS RETURN',money(r.excess_return)),metric('WIN RATE',pct(r.win_rate)),metric('EXPECTANCY',money(r.expectancy)),metric('PROFIT FACTOR',r.profit_factor===null?'∞':Number(r.profit_factor||0).toFixed(2)),metric('CLOSED TRADES',String(r.closed_trades??0)))}
 window.addEventListener('desk-data',event=>{ensurePanel();const data=event.detail;renderRisk(data);renderAnalytics(data);renderSafety(data);renderRegimes(data);renderSources(data);renderDecisions(data);renderReplay(data)});
})();
