(() => {
 const node=(tag,text='',cls='')=>{const el=document.createElement(tag);el.textContent=text;if(cls)el.className=cls;return el;};
 const valid=a=>typeof a==='string'&&/^[1-9A-HJ-NP-Za-km-z]{32,44}$/.test(a);
 const money=n=>Number.isFinite(n)?new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(n):'Not supplied';
 const when=t=>Number.isFinite(t)?new Date(t).toLocaleString():'Not recorded';
 let state=null,pending=false,selected='',dialog,apiInput,dialogStatus,dialogBudget,connectButton,testButton,disconnectButton;
 const panel=node('section','','panel wallet-research');panel.id='wallet-research';
 const head=node('div','','panel-head');head.append(node('h2','WALLET RESEARCH / SOLANA'),node('span','READ ONLY'));panel.append(head);
 panel.append(node('p','Explore platform-tagged wallet activity and provider-reported results. These are research leads, not verified profitable wallets or executable copy trades.','wallet-help'));
 const controls=node('div','','wallet-controls'),setup=node('button','GMGN connection','gmgn-setup-access'),refresh=node('button','Refresh saved view');setup.type=refresh.type='button';setup.onclick=()=>openSetup();refresh.onclick=()=>load();controls.append(setup,refresh);panel.append(controls);
 const connection=node('p','','wallet-connection'),budget=node('p','','wallet-budget'),status=node('p','','wallet-status');status.setAttribute('role','status');panel.append(connection,budget,status);
 const columns=node('div','','wallet-columns'),left=node('section','','wallet-column'),right=node('section','','wallet-column');columns.append(left,right);panel.append(columns);
 left.append(node('h3','Discover smart-money activity'),node('p','Discovery shows recent wallets tagged by the platform. It is not a profitability ranking.','wallet-help'));
 const discover=node('button','Discover wallets');discover.type='button';discover.onclick=()=>action('/api/wallets/discover',{},'Discovery updated.');left.append(discover);
 const discovered=node('div','','wallet-list');left.append(discovered,node('h3','Watchlist'));
 const watchForm=node('form','','wallet-form'),watchAddress=node('input'),watchLabel=node('input'),watchButton=node('button','Add to watchlist');
 watchAddress.placeholder='Solana wallet address';watchAddress.maxLength=44;watchAddress.required=true;watchAddress.pattern='[1-9A-HJ-NP-Za-km-z]{32,44}';watchAddress.setAttribute('aria-label','Wallet address to watch');watchLabel.placeholder='Label (optional)';watchLabel.maxLength=60;watchLabel.setAttribute('aria-label','Watchlist label');watchButton.type='submit';watchForm.append(watchAddress,watchLabel,watchButton);watchForm.onsubmit=e=>{e.preventDefault();const address=watchAddress.value.trim();if(!valid(address)){status.textContent='Enter a valid Solana wallet address.';return;}action('/api/wallets/watch',{action:'add',address,label:watchLabel.value.trim()},'Wallet added to the watchlist.').then(ok=>{if(ok){watchAddress.value='';watchLabel.value='';}});};left.append(watchForm);
 const watched=node('div','','wallet-list');left.append(watched);
 right.append(node('h3','Analyze a wallet'));
 const analyzeForm=node('form','','wallet-form'),analyzeAddress=node('input'),period=node('select'),analyze=node('button','Analyze selected period');
 analyzeAddress.placeholder='Select or paste a Solana wallet address';analyzeAddress.maxLength=44;analyzeAddress.required=true;analyzeAddress.pattern='[1-9A-HJ-NP-Za-km-z]{32,44}';analyzeAddress.setAttribute('aria-label','Wallet address to analyze');period.setAttribute('aria-label','Wallet analysis period');for(const [value,label]of [['7d','Last 7 days'],['30d','Last 30 days']]){const opt=node('option',label);opt.value=value;period.append(opt);}analyze.type='submit';analyzeForm.append(analyzeAddress,period,analyze);analyzeForm.onsubmit=e=>{e.preventDefault();const address=analyzeAddress.value.trim();if(!valid(address)){status.textContent='Enter a valid Solana wallet address.';return;}selected=address;action('/api/wallets/analyze',{address,period:period.value},'Provider-reported period analysis saved.');};right.append(analyzeForm);
 right.append(node('p','Each analysis is one manual provider request. Recent trades are loaded separately, on request.','wallet-help'));const reports=node('div','','wallet-reports');right.append(reports);
 panel.append(node('p','No wallet keys, signing files, funds, or trading permissions are requested. Results omit complete transaction history and cannot establish copy-trading returns.','wallet-help'));
 const mount=document.querySelector('#research-room')||document.querySelector('#learning-lab')||document.querySelector('.markets-panel');if(mount)mount.after(panel);else(document.querySelector('main')||document.body).append(panel);
 function external(label,address){const a=node('a',label);if(valid(address)){a.href='https://gmgn.ai/sol/address/'+encodeURIComponent(address);a.target='_blank';a.rel='noopener noreferrer';}return a;}
 function providerReason(requireConnection=true){const limits=state?.limits||{};if(limits.busy)return 'A provider request is already running.';if(Number.isFinite(limits.remaining_today)&&limits.remaining_today<=0)return 'The daily provider request budget is exhausted.';const deadline=Math.max(Number(limits.next_request_at)||0,Number(limits.cooldown_until)||0);if(deadline>Date.now())return 'Next provider request in '+Math.ceil((deadline-Date.now())/1000)+' seconds.';return requireConnection&&!state?.connection?.configured?'Connect GMGN to request provider data.':'';}
 function updateControls(){const reason=providerReason();discover.disabled=analyze.disabled=pending||!!reason;refresh.disabled=watchButton.disabled=pending;for(const button of panel.querySelectorAll('[data-wallet-action]'))button.disabled=pending||(button.dataset.walletAction==='provider'&&!!reason)||(button.dataset.walletAction==='watch'&&(state?.watchlist||[]).length>=10);const limits=state?.limits;budget.textContent=(limits?`${limits.requests_today??0}/${limits.max_daily_requests??100} provider requests today · ${limits.remaining_today??'—'} remaining. `:'')+reason;if(dialog){dialogBudget.textContent=budget.textContent;const secure=state?.connection?.secure_setup_ready===true;apiInput.disabled=pending||!secure;connectButton.disabled=pending||!secure||!!providerReason(false);testButton.disabled=pending||!!reason;disconnectButton.disabled=pending;}}
 function render(){const c=state?.connection;connection.textContent=!state?'Loading saved wallet research…':c?.configured?`GMGN ${String(c.status||'configured').replaceAll('_',' ')} · read-only${c.verified_at?' · verified '+when(c.verified_at):''}${c.error?' · '+c.error:''}`:'GMGN is not connected. Open GMGN connection to securely add an API key. You can maintain a watchlist before connecting.';discovered.replaceChildren();watched.replaceChildren();reports.replaceChildren();
  const wallets=state?.discovery?.wallets||[];if(!wallets.length)discovered.append(node('p','No saved discoveries yet. Discovery runs only when you click Discover wallets.','wallet-help'));else{discovered.append(node('small','Saved discovery: '+when(state.discovery.at)));for(const item of wallets)discovered.append(walletCard(item,false));}
  const list=state?.watchlist||[];if(!list.length)watched.append(node('p','Add an address to follow its saved research.','wallet-help'));for(const item of list)watched.append(walletCard(item,true));
  if(!state?.reports?.length)reports.append(node('p','No saved wallet analysis yet. Select a wallet, choose a period, and run a manual analysis.','wallet-help'));
  const visibleReports=(state?.reports||[]).filter(report=>!selected||report.address===selected).slice(0,20);if(selected&&!visibleReports.length&&state?.reports?.length)reports.append(node('p','No saved report for the selected wallet. Run an analysis to load its results.','wallet-help'));for(const report of visibleReports)reports.append(reportCard(report));updateControls();
 }
 function walletCard(item,isWatched){const card=node('article','','wallet-record');card.append(node('b',item.label||'Solana wallet'),node('code',item.address));if(item.last_side)card.append(node('small','Last observed activity: '+item.last_side));const row=node('div','','wallet-controls'),select=node('button',selected===item.address?'Selected':'Select wallet');select.type='button';select.dataset.walletAction='local';select.onclick=()=>{selected=item.address;analyzeAddress.value=item.address;render();analyzeAddress.focus();};row.append(select,external('View on GMGN',item.address));if(!isWatched){const follow=node('button','Watch wallet');follow.type='button';follow.dataset.walletAction='watch';follow.onclick=()=>action('/api/wallets/watch',{action:'add',address:item.address,label:item.label||''},'Wallet added to the watchlist.');follow.disabled=(state?.watchlist||[]).length>=10;row.append(follow);}if(isWatched){const remove=node('button','Remove');remove.type='button';remove.dataset.walletAction='local';remove.onclick=()=>action('/api/wallets/watch',{action:'remove',address:item.address},'Wallet removed from the watchlist.');row.append(remove);}card.append(row);return card;}
 function reportCard(report){const card=node('article','','wallet-report');card.append(node('h4',(report.period==='30d'?'30-day':'7-day')+' provider report'),node('code',report.address),node('small','Retrieved '+when(report.at)));const metrics=node('dl','','wallet-metrics');for(const [label,value]of [['Provider realized profit',money(report.realized_profit)],['Provider realized cost basis',money(report.realized_profit_cost)],['Profit / reported cost',Number.isFinite(report.realized_roi)?(report.realized_roi*100).toFixed(2)+'%':'Not supplied'],['Provider buy / sell counts',(Number.isFinite(report.buy_count)?report.buy_count:'—')+' / '+(Number.isFinite(report.sell_count)?report.sell_count:'—')]]){const cell=node('div');cell.append(node('dt',label),node('dd',value));metrics.append(cell);}card.append(metrics,node('p',report.note||'Provider-reported values are not independently verified performance. Profit divided by reported cost is a cost-basis ratio, not the return on an account balance.','wallet-help'));
  card.append(node('p','Profit / reported cost is a cost-basis ratio, not the return on an account balance.','wallet-help'));const history=node('button','Load recent trades');history.type='button';history.dataset.walletAction='provider';history.onclick=()=>action('/api/wallets/activity',{address:report.address},'Recent trade sample saved. This is partial history.');card.append(history,document.createTextNode(' '),external('View wallet on GMGN',report.address));
  const activities=report.activities||[];card.append(node('p',report.history_status==='partial'?`Partial history sample · ${activities.length} recent records${report.history_has_more?' · additional history exists':''}. This is not a full wallet backtest.`:'Transaction history has not been loaded. Period P&L alone cannot verify complete returns.','wallet-help'));
  if(activities.length){const wrap=node('div','','wallet-table-scroll');wrap.tabIndex=0;wrap.setAttribute('role','region');wrap.setAttribute('aria-label','Recent wallet activity sample');const table=node('table'),thead=node('thead'),tr=node('tr');for(const label of ['Observed time','Activity','Token','USD amount'])tr.append(node('th',label));thead.append(tr);table.append(thead);const body=node('tbody');for(const item of activities.slice(0,10)){const row=node('tr');row.append(node('td',when(item.at)),node('td',item.side||'Not supplied'),node('td',item.symbol||'Not supplied'),node('td',money(item.amount_usd)));body.append(row);}table.append(body);wrap.append(table);card.append(wrap);}return card;}
 async function load(){if(pending)return;pending=true;updateControls();try{const response=await fetch('/api/wallets'),value=await response.json();if(!response.ok)throw Error(value.error||'Could not load saved wallet research.');state=value;render();}catch(error){status.textContent=error.message;}finally{pending=false;updateControls();}}
 async function action(path,body,message){if(pending)return false;pending=true;status.textContent='Processing your request…';if(dialogStatus)dialogStatus.textContent='Processing your request…';updateControls();try{const response=await fetch(path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});if(body.api_key)body.api_key='';const value=await response.json();if(!response.ok){if(value.limits){state={...state,limits:value.limits};render();}throw Error(value.error||'Wallet request failed.');}state=value;render();status.textContent=message;if(dialogStatus)dialogStatus.textContent=message;window.dispatchEvent(new CustomEvent('wallets-updated',{detail:state}));return true;}catch(error){try{const cached=await fetch('/api/wallets'),value=await cached.json();if(cached.ok){state=value;render();}}catch{}status.textContent=error.message;if(dialogStatus)dialogStatus.textContent=error.message;return false;}finally{if(body.api_key)body.api_key='';pending=false;updateControls();}}
 function official(label,url){const a=node('a',label);a.href=url;a.target='_blank';a.rel='noopener noreferrer';return a;}
 function openSetup(){if(!dialog){dialog=node('dialog','','wallet-setup');dialog.id='gmgn-setup';const close=node('button','×','wallet-close');close.type='button';close.setAttribute('aria-label','Close GMGN setup');close.onclick=()=>dialog.close();dialog.append(close,node('small','DOTSTRADING / SECURE CONNECTION'),node('h2','Connect GMGN for wallet research'),node('p','This initial read-only connection needs a GMGN API key only. Dots never requests your wallet seed phrase or private request-signing key.','wallet-help'));dialogStatus=node('p','','wallet-status');dialogStatus.setAttribute('role','status');dialogBudget=node('p','','wallet-budget');dialog.append(dialogStatus,dialogBudget);
   const form=node('form','','wallet-form');form.autocomplete='off';const label=node('label','GMGN API key');apiInput=node('input');apiInput.type='password';apiInput.name='api_key';apiInput.autocomplete='off';apiInput.spellcheck=false;apiInput.maxLength=512;apiInput.required=true;label.append(apiInput);connectButton=node('button','Verify & save API key');connectButton.type='submit';form.append(label,node('p','The key is verified on your request, then encrypted on the server. It is never returned to this screen or included in exports.','wallet-help'),connectButton);form.onsubmit=e=>{e.preventDefault();const api_key=apiInput.value;apiInput.value='';action('/api/wallets/connection',{action:'connect',api_key},'GMGN API access verified and connection saved.');};dialog.append(form);
   const buttons=node('div','','wallet-controls');testButton=node('button','Test connection');disconnectButton=node('button','Disconnect GMGN');testButton.type=disconnectButton.type='button';testButton.onclick=()=>action('/api/wallets/connection',{action:'test'},'Connection check completed.');disconnectButton.onclick=()=>action('/api/wallets/connection',{action:'disconnect'},'GMGN disconnected. Provider requests are disabled until you reconnect.');buttons.append(testButton,disconnectButton);dialog.append(buttons);
   const generation=node('section','','wallet-key-generator');generation.append(node('h3','Create a GMGN API key'),node('p','GMGN asks for a request-signing public key when issuing an API key. Generate a pair in this browser and save the private PEM file on your device for GMGN. Dots will not receive that file.','wallet-help'),official('Official public-key guide','https://docs.gmgn.ai/index/generate-public-key'),document.createTextNode(' · '),official('GMGN Agent API guide','https://docs.gmgn.ai/index/gmgn-agent-api'));
   const generate=node('button','Generate & download signing key');generate.type='button';generate.id='gmgn-generate-key';const keyStatus=node('p','','wallet-status');keyStatus.setAttribute('role','status');const publicLabel=node('label','Public key only'),publicKey=node('textarea');publicKey.id='gmgn-public-key';publicKey.readOnly=true;publicKey.rows=5;publicKey.setAttribute('aria-label','Generated public key PEM');publicLabel.append(publicKey);publicLabel.hidden=true;const publicControls=node('div','','wallet-controls');publicControls.hidden=true;const copy=node('button','Copy public key'),create=official('Create API key on GMGN','https://gmgn.ai/ai/generateapi');copy.type='button';create.id='gmgn-create-api';copy.onclick=async()=>{try{await navigator.clipboard.writeText(publicKey.value);keyStatus.textContent='Public key copied.';}catch{publicKey.focus();publicKey.select();keyStatus.textContent='Select and copy the public key shown above.';}};publicControls.append(copy,create);
   generate.onclick=async()=>{generate.disabled=true;keyStatus.textContent='Generating your request-signing key locally…';let keys,privateBytes,privatePem='';try{if(!window.isSecureContext||!crypto.subtle)throw Error('This browser needs a secure HTTPS context to generate keys. Use the official public-key guide.');keys=await crypto.subtle.generateKey({name:'Ed25519'},true,['sign','verify']);const exports=await Promise.all([crypto.subtle.exportKey('spki',keys.publicKey),crypto.subtle.exportKey('pkcs8',keys.privateKey)]);privateBytes=new Uint8Array(exports[1]);const pem=(type,bytes)=>'-----BEGIN '+type+'-----\n'+btoa(Array.from(bytes,b=>String.fromCharCode(b)).join('')).match(/.{1,64}/g).join('\n')+'\n-----END '+type+'-----\n';const publicPem=pem('PUBLIC KEY',new Uint8Array(exports[0]));privatePem=pem('PRIVATE KEY',privateBytes);const blob=new Blob([privatePem],{type:'application/x-pem-file'}),url=URL.createObjectURL(blob),download=node('a');download.href=url;download.download='dots-gmgn-request-signing-key.pem';document.body.append(download);download.click();download.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);privateBytes.fill(0);privatePem='';keys=null;publicKey.value=publicPem;publicLabel.hidden=false;publicControls.hidden=false;const officialUrl=new URL('https://gmgn.ai/ai/generateapi');officialUrl.searchParams.set('pbk',publicPem);create.href=officialUrl.href;keyStatus.textContent='Private signing PEM downloaded to your device. Keep it private. Only the public key is included in the GMGN registration link. Paste the issued API key into the connection form above.';}catch(error){keyStatus.textContent='Key generation unavailable: '+error.message+' Follow the official guide using a supported browser or local tools.';}finally{if(privateBytes)privateBytes.fill(0);privatePem='';keys=null;generate.disabled=false;}};
   generation.append(generate,keyStatus,publicLabel,publicControls);dialog.append(generation);dialog.addEventListener('close',()=>{apiInput.value='';});document.body.append(dialog);
  }
  const c=state?.connection;dialogStatus.textContent=c?.configured?'GMGN '+String(c.status||'configured').replaceAll('_',' ')+' · read-only'+(c.source==='hosting'?' · configured by hosting settings':''):'No API key connected.';if(!c?.secure_setup_ready)dialogStatus.textContent+=' Secure server setup is not available yet.';updateControls();dialog.showModal();
 }
 window.addEventListener('desk-data',event=>{if(event.detail.wallets&&!pending){state=event.detail.wallets;render();}});
 if(window.dotsDeskData?.wallets){state=window.dotsDeskData.wallets;render();}else{render();load();}
 setInterval(updateControls,1000);
})();
